// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matrix_multiply_32x32_Loop_VITIS_LOOP_57_3_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem_b_AWVALID,
        m_axi_gmem_b_AWREADY,
        m_axi_gmem_b_AWADDR,
        m_axi_gmem_b_AWID,
        m_axi_gmem_b_AWLEN,
        m_axi_gmem_b_AWSIZE,
        m_axi_gmem_b_AWBURST,
        m_axi_gmem_b_AWLOCK,
        m_axi_gmem_b_AWCACHE,
        m_axi_gmem_b_AWPROT,
        m_axi_gmem_b_AWQOS,
        m_axi_gmem_b_AWREGION,
        m_axi_gmem_b_AWUSER,
        m_axi_gmem_b_WVALID,
        m_axi_gmem_b_WREADY,
        m_axi_gmem_b_WDATA,
        m_axi_gmem_b_WSTRB,
        m_axi_gmem_b_WLAST,
        m_axi_gmem_b_WID,
        m_axi_gmem_b_WUSER,
        m_axi_gmem_b_ARVALID,
        m_axi_gmem_b_ARREADY,
        m_axi_gmem_b_ARADDR,
        m_axi_gmem_b_ARID,
        m_axi_gmem_b_ARLEN,
        m_axi_gmem_b_ARSIZE,
        m_axi_gmem_b_ARBURST,
        m_axi_gmem_b_ARLOCK,
        m_axi_gmem_b_ARCACHE,
        m_axi_gmem_b_ARPROT,
        m_axi_gmem_b_ARQOS,
        m_axi_gmem_b_ARREGION,
        m_axi_gmem_b_ARUSER,
        m_axi_gmem_b_RVALID,
        m_axi_gmem_b_RREADY,
        m_axi_gmem_b_RDATA,
        m_axi_gmem_b_RLAST,
        m_axi_gmem_b_RID,
        m_axi_gmem_b_RFIFONUM,
        m_axi_gmem_b_RUSER,
        m_axi_gmem_b_RRESP,
        m_axi_gmem_b_BVALID,
        m_axi_gmem_b_BREADY,
        m_axi_gmem_b_BRESP,
        m_axi_gmem_b_BID,
        m_axi_gmem_b_BUSER,
        B,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        b_stream_din,
        b_stream_num_data_valid,
        b_stream_fifo_cap,
        b_stream_full_n,
        b_stream_write
);

parameter    ap_ST_fsm_pp0_stage0 = 32'd1;
parameter    ap_ST_fsm_pp0_stage1 = 32'd2;
parameter    ap_ST_fsm_pp0_stage2 = 32'd4;
parameter    ap_ST_fsm_pp0_stage3 = 32'd8;
parameter    ap_ST_fsm_pp0_stage4 = 32'd16;
parameter    ap_ST_fsm_pp0_stage5 = 32'd32;
parameter    ap_ST_fsm_pp0_stage6 = 32'd64;
parameter    ap_ST_fsm_pp0_stage7 = 32'd128;
parameter    ap_ST_fsm_pp0_stage8 = 32'd256;
parameter    ap_ST_fsm_pp0_stage9 = 32'd512;
parameter    ap_ST_fsm_pp0_stage10 = 32'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 32'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 32'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 32'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 32'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 32'd32768;
parameter    ap_ST_fsm_pp0_stage16 = 32'd65536;
parameter    ap_ST_fsm_pp0_stage17 = 32'd131072;
parameter    ap_ST_fsm_pp0_stage18 = 32'd262144;
parameter    ap_ST_fsm_pp0_stage19 = 32'd524288;
parameter    ap_ST_fsm_pp0_stage20 = 32'd1048576;
parameter    ap_ST_fsm_pp0_stage21 = 32'd2097152;
parameter    ap_ST_fsm_pp0_stage22 = 32'd4194304;
parameter    ap_ST_fsm_pp0_stage23 = 32'd8388608;
parameter    ap_ST_fsm_pp0_stage24 = 32'd16777216;
parameter    ap_ST_fsm_pp0_stage25 = 32'd33554432;
parameter    ap_ST_fsm_pp0_stage26 = 32'd67108864;
parameter    ap_ST_fsm_pp0_stage27 = 32'd134217728;
parameter    ap_ST_fsm_pp0_stage28 = 32'd268435456;
parameter    ap_ST_fsm_pp0_stage29 = 32'd536870912;
parameter    ap_ST_fsm_pp0_stage30 = 32'd1073741824;
parameter    ap_ST_fsm_pp0_stage31 = 32'd2147483648;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_b_AWVALID;
input   m_axi_gmem_b_AWREADY;
output  [63:0] m_axi_gmem_b_AWADDR;
output  [0:0] m_axi_gmem_b_AWID;
output  [31:0] m_axi_gmem_b_AWLEN;
output  [2:0] m_axi_gmem_b_AWSIZE;
output  [1:0] m_axi_gmem_b_AWBURST;
output  [1:0] m_axi_gmem_b_AWLOCK;
output  [3:0] m_axi_gmem_b_AWCACHE;
output  [2:0] m_axi_gmem_b_AWPROT;
output  [3:0] m_axi_gmem_b_AWQOS;
output  [3:0] m_axi_gmem_b_AWREGION;
output  [0:0] m_axi_gmem_b_AWUSER;
output   m_axi_gmem_b_WVALID;
input   m_axi_gmem_b_WREADY;
output  [7:0] m_axi_gmem_b_WDATA;
output  [0:0] m_axi_gmem_b_WSTRB;
output   m_axi_gmem_b_WLAST;
output  [0:0] m_axi_gmem_b_WID;
output  [0:0] m_axi_gmem_b_WUSER;
output   m_axi_gmem_b_ARVALID;
input   m_axi_gmem_b_ARREADY;
output  [63:0] m_axi_gmem_b_ARADDR;
output  [0:0] m_axi_gmem_b_ARID;
output  [31:0] m_axi_gmem_b_ARLEN;
output  [2:0] m_axi_gmem_b_ARSIZE;
output  [1:0] m_axi_gmem_b_ARBURST;
output  [1:0] m_axi_gmem_b_ARLOCK;
output  [3:0] m_axi_gmem_b_ARCACHE;
output  [2:0] m_axi_gmem_b_ARPROT;
output  [3:0] m_axi_gmem_b_ARQOS;
output  [3:0] m_axi_gmem_b_ARREGION;
output  [0:0] m_axi_gmem_b_ARUSER;
input   m_axi_gmem_b_RVALID;
output   m_axi_gmem_b_RREADY;
input  [7:0] m_axi_gmem_b_RDATA;
input   m_axi_gmem_b_RLAST;
input  [0:0] m_axi_gmem_b_RID;
input  [10:0] m_axi_gmem_b_RFIFONUM;
input  [0:0] m_axi_gmem_b_RUSER;
input  [1:0] m_axi_gmem_b_RRESP;
input   m_axi_gmem_b_BVALID;
output   m_axi_gmem_b_BREADY;
input  [1:0] m_axi_gmem_b_BRESP;
input  [0:0] m_axi_gmem_b_BID;
input  [0:0] m_axi_gmem_b_BUSER;
input  [63:0] B;
input  [63:0] p_read;
input  [63:0] p_read1;
input  [63:0] p_read2;
input  [63:0] p_read3;
input  [63:0] p_read4;
input  [63:0] p_read5;
input  [63:0] p_read6;
input  [63:0] p_read7;
input  [63:0] p_read8;
input  [63:0] p_read9;
input  [63:0] p_read10;
input  [63:0] p_read11;
input  [63:0] p_read12;
input  [63:0] p_read13;
input  [63:0] p_read14;
input  [63:0] p_read15;
input  [63:0] p_read16;
input  [63:0] p_read17;
input  [63:0] p_read18;
input  [63:0] p_read19;
input  [63:0] p_read20;
input  [63:0] p_read21;
input  [63:0] p_read22;
input  [63:0] p_read23;
input  [63:0] p_read24;
input  [63:0] p_read25;
input  [63:0] p_read26;
input  [63:0] p_read27;
input  [63:0] p_read28;
input  [63:0] p_read29;
input  [63:0] p_read30;
output  [255:0] b_stream_din;
input  [2:0] b_stream_num_data_valid;
input  [2:0] b_stream_fifo_cap;
input   b_stream_full_n;
output   b_stream_write;

reg ap_idle;
reg m_axi_gmem_b_ARVALID;
reg[63:0] m_axi_gmem_b_ARADDR;
reg m_axi_gmem_b_RREADY;

(* fsm_encoding = "none" *) reg   [31:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage31;
reg    ap_block_state32_pp0_stage31_iter0;
reg    ap_block_pp0_stage31_subdone;
reg   [0:0] icmp_ln57_reg_1352;
reg    ap_condition_exit_pp0_iter0_stage31;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_b_blk_n_AR;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg    gmem_b_blk_n_R;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_pp0_stage13;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_pp0_stage14;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7;
wire    ap_CS_fsm_pp0_stage15;
wire    ap_block_pp0_stage15;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8;
wire    ap_CS_fsm_pp0_stage16;
wire    ap_block_pp0_stage16;
wire    ap_CS_fsm_pp0_stage17;
wire    ap_block_pp0_stage17;
wire    ap_CS_fsm_pp0_stage18;
wire    ap_block_pp0_stage18;
wire    ap_CS_fsm_pp0_stage19;
wire    ap_block_pp0_stage19;
wire    ap_CS_fsm_pp0_stage20;
wire    ap_block_pp0_stage20;
wire    ap_CS_fsm_pp0_stage21;
wire    ap_block_pp0_stage21;
wire    ap_CS_fsm_pp0_stage22;
wire    ap_block_pp0_stage22;
wire    ap_CS_fsm_pp0_stage23;
wire    ap_block_pp0_stage23;
wire    ap_CS_fsm_pp0_stage24;
wire    ap_block_pp0_stage24;
wire    ap_CS_fsm_pp0_stage25;
wire    ap_block_pp0_stage25;
wire    ap_CS_fsm_pp0_stage26;
wire    ap_block_pp0_stage26;
wire    ap_CS_fsm_pp0_stage27;
wire    ap_block_pp0_stage27;
wire    ap_CS_fsm_pp0_stage28;
wire    ap_block_pp0_stage28;
wire    ap_CS_fsm_pp0_stage29;
wire    ap_block_pp0_stage29;
wire    ap_CS_fsm_pp0_stage30;
wire    ap_block_pp0_stage30;
wire    ap_block_pp0_stage31;
wire    ap_block_pp0_stage0;
reg    b_stream_blk_n;
reg   [63:0] gmem_b_addr_reg_1160;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state33_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] gmem_b_addr_1_reg_1166;
reg   [63:0] gmem_b_addr_2_reg_1172;
reg   [63:0] gmem_b_addr_3_reg_1178;
reg   [63:0] gmem_b_addr_4_reg_1184;
reg   [63:0] gmem_b_addr_5_reg_1190;
reg   [63:0] gmem_b_addr_6_reg_1196;
reg   [63:0] gmem_b_addr_7_reg_1202;
reg   [63:0] gmem_b_addr_8_reg_1208;
reg   [63:0] gmem_b_addr_9_reg_1214;
reg   [63:0] gmem_b_addr_10_reg_1220;
reg   [63:0] gmem_b_addr_11_reg_1226;
reg   [63:0] gmem_b_addr_12_reg_1232;
reg   [63:0] gmem_b_addr_13_reg_1238;
reg   [63:0] gmem_b_addr_14_reg_1244;
reg   [63:0] gmem_b_addr_15_reg_1250;
reg   [63:0] gmem_b_addr_16_reg_1256;
reg   [63:0] gmem_b_addr_17_reg_1262;
reg   [63:0] gmem_b_addr_18_reg_1268;
reg   [63:0] gmem_b_addr_19_reg_1274;
reg   [63:0] gmem_b_addr_20_reg_1280;
reg   [63:0] gmem_b_addr_21_reg_1286;
reg   [63:0] gmem_b_addr_22_reg_1292;
reg   [63:0] gmem_b_addr_23_reg_1298;
reg   [63:0] gmem_b_addr_24_reg_1304;
reg   [63:0] gmem_b_addr_25_reg_1310;
reg   [63:0] gmem_b_addr_26_reg_1316;
reg   [63:0] gmem_b_addr_27_reg_1322;
reg   [63:0] gmem_b_addr_28_reg_1328;
reg   [63:0] gmem_b_addr_29_reg_1334;
reg   [63:0] gmem_b_addr_30_reg_1340;
reg   [63:0] gmem_b_addr_31_reg_1346;
wire   [0:0] icmp_ln57_fu_1105_p2;
reg   [0:0] icmp_ln57_reg_1352_pp0_iter1_reg;
reg   [7:0] gmem_b_addr_read_reg_1356;
reg    ap_block_state10_pp0_stage9_iter0;
reg    ap_block_state42_pp0_stage9_iter1;
reg    ap_block_pp0_stage9_11001;
reg   [7:0] gmem_b_addr_1_read_reg_1361;
reg    ap_block_state11_pp0_stage10_iter0;
reg    ap_block_pp0_stage10_11001;
reg   [7:0] gmem_b_addr_2_read_reg_1366;
reg    ap_block_state12_pp0_stage11_iter0;
reg    ap_block_pp0_stage11_11001;
reg   [7:0] gmem_b_addr_3_read_reg_1371;
reg    ap_block_state13_pp0_stage12_iter0;
reg    ap_block_pp0_stage12_11001;
reg   [7:0] gmem_b_addr_4_read_reg_1376;
reg    ap_block_state14_pp0_stage13_iter0;
reg    ap_block_pp0_stage13_11001;
reg   [7:0] gmem_b_addr_5_read_reg_1381;
reg    ap_block_state15_pp0_stage14_iter0;
reg    ap_block_pp0_stage14_11001;
reg   [7:0] gmem_b_addr_6_read_reg_1386;
reg    ap_block_state16_pp0_stage15_iter0;
reg    ap_block_pp0_stage15_11001;
reg   [7:0] gmem_b_addr_7_read_reg_1391;
reg    ap_block_state17_pp0_stage16_iter0;
reg    ap_block_pp0_stage16_11001;
reg   [7:0] gmem_b_addr_8_read_reg_1396;
reg    ap_block_state18_pp0_stage17_iter0;
reg    ap_block_pp0_stage17_11001;
reg   [7:0] gmem_b_addr_9_read_reg_1401;
reg    ap_block_state19_pp0_stage18_iter0;
reg    ap_block_pp0_stage18_11001;
reg   [7:0] gmem_b_addr_10_read_reg_1406;
reg    ap_block_state20_pp0_stage19_iter0;
reg    ap_block_pp0_stage19_11001;
reg   [7:0] gmem_b_addr_11_read_reg_1411;
reg    ap_block_state21_pp0_stage20_iter0;
reg    ap_block_pp0_stage20_11001;
reg   [7:0] gmem_b_addr_12_read_reg_1416;
reg    ap_block_state22_pp0_stage21_iter0;
reg    ap_block_pp0_stage21_11001;
reg   [7:0] gmem_b_addr_13_read_reg_1421;
reg    ap_block_state23_pp0_stage22_iter0;
reg    ap_block_pp0_stage22_11001;
reg   [7:0] gmem_b_addr_14_read_reg_1426;
reg    ap_block_state24_pp0_stage23_iter0;
reg    ap_block_pp0_stage23_11001;
reg   [7:0] gmem_b_addr_15_read_reg_1431;
reg    ap_block_state25_pp0_stage24_iter0;
reg    ap_block_pp0_stage24_11001;
reg   [7:0] gmem_b_addr_16_read_reg_1436;
reg    ap_block_state26_pp0_stage25_iter0;
reg    ap_block_pp0_stage25_11001;
reg   [7:0] gmem_b_addr_17_read_reg_1441;
reg    ap_block_state27_pp0_stage26_iter0;
reg    ap_block_pp0_stage26_11001;
reg   [7:0] gmem_b_addr_18_read_reg_1446;
reg    ap_block_state28_pp0_stage27_iter0;
reg    ap_block_pp0_stage27_11001;
reg   [7:0] gmem_b_addr_19_read_reg_1451;
reg    ap_block_state29_pp0_stage28_iter0;
reg    ap_block_pp0_stage28_11001;
reg   [7:0] gmem_b_addr_20_read_reg_1456;
reg    ap_block_state30_pp0_stage29_iter0;
reg    ap_block_pp0_stage29_11001;
reg   [7:0] gmem_b_addr_21_read_reg_1461;
reg    ap_block_state31_pp0_stage30_iter0;
reg    ap_block_pp0_stage30_11001;
reg   [7:0] gmem_b_addr_22_read_reg_1466;
reg    ap_block_pp0_stage31_11001;
reg   [7:0] gmem_b_addr_23_read_reg_1471;
reg   [7:0] gmem_b_addr_24_read_reg_1476;
reg    ap_block_state34_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
reg   [7:0] gmem_b_addr_25_read_reg_1481;
reg    ap_block_state35_pp0_stage2_iter1;
reg    ap_block_pp0_stage2_11001;
reg   [7:0] gmem_b_addr_26_read_reg_1486;
reg    ap_block_state36_pp0_stage3_iter1;
reg    ap_block_pp0_stage3_11001;
reg   [7:0] gmem_b_addr_27_read_reg_1491;
reg    ap_block_state37_pp0_stage4_iter1;
reg    ap_block_pp0_stage4_11001;
reg   [7:0] gmem_b_addr_28_read_reg_1496;
reg    ap_block_state38_pp0_stage5_iter1;
reg    ap_block_pp0_stage5_11001;
reg   [7:0] gmem_b_addr_29_read_reg_1501;
reg    ap_block_state39_pp0_stage6_iter1;
reg    ap_block_pp0_stage6_11001;
reg   [7:0] gmem_b_addr_30_read_reg_1506;
reg    ap_block_state40_pp0_stage7_iter1;
reg    ap_block_pp0_stage7_11001;
reg   [7:0] gmem_b_addr_31_read_reg_1511;
reg    ap_block_state41_pp0_stage8_iter1;
reg    ap_block_pp0_stage8_11001;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage9_subdone;
wire   [63:0] add_ln60_fu_715_p2;
wire   [63:0] add_ln60_1_fu_727_p2;
wire   [63:0] add_ln60_2_fu_739_p2;
wire   [63:0] add_ln60_3_fu_751_p2;
wire   [63:0] add_ln60_4_fu_763_p2;
wire   [63:0] add_ln60_5_fu_775_p2;
wire   [63:0] add_ln60_6_fu_787_p2;
wire   [63:0] add_ln60_7_fu_799_p2;
wire   [63:0] add_ln60_8_fu_811_p2;
wire   [63:0] add_ln60_9_fu_823_p2;
wire   [63:0] add_ln60_10_fu_835_p2;
wire   [63:0] add_ln60_11_fu_847_p2;
wire   [63:0] add_ln60_12_fu_859_p2;
wire   [63:0] add_ln60_13_fu_871_p2;
wire   [63:0] add_ln60_14_fu_883_p2;
wire   [63:0] add_ln60_15_fu_895_p2;
wire   [63:0] add_ln60_16_fu_907_p2;
wire   [63:0] add_ln60_17_fu_919_p2;
wire   [63:0] add_ln60_18_fu_931_p2;
wire   [63:0] add_ln60_19_fu_943_p2;
wire   [63:0] add_ln60_20_fu_955_p2;
wire   [63:0] add_ln60_21_fu_967_p2;
wire   [63:0] add_ln60_22_fu_979_p2;
wire   [63:0] add_ln60_23_fu_991_p2;
wire   [63:0] add_ln60_24_fu_1003_p2;
wire   [63:0] add_ln60_25_fu_1015_p2;
wire   [63:0] add_ln60_26_fu_1027_p2;
wire   [63:0] add_ln60_27_fu_1039_p2;
wire   [63:0] add_ln60_28_fu_1051_p2;
wire   [63:0] add_ln60_29_fu_1063_p2;
wire   [63:0] add_ln60_30_fu_1075_p2;
wire   [63:0] add_ln60_31_fu_1087_p2;
reg   [4:0] j94_fu_116;
wire   [4:0] j_fu_1099_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j94_load;
wire   [255:0] col_b_fu_1116_p33;
reg    ap_block_pp0_stage9_01001;
reg    b_stream_write_local;
wire   [63:0] zext_ln57_fu_711_p1;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage9;
reg    ap_idle_pp0_0to0;
reg   [31:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_block_pp0_stage7_subdone;
reg    ap_block_pp0_stage8_subdone;
reg    ap_block_pp0_stage10_subdone;
reg    ap_block_pp0_stage11_subdone;
reg    ap_block_pp0_stage12_subdone;
reg    ap_block_pp0_stage13_subdone;
reg    ap_block_pp0_stage14_subdone;
reg    ap_block_pp0_stage15_subdone;
reg    ap_block_pp0_stage16_subdone;
reg    ap_block_pp0_stage17_subdone;
reg    ap_block_pp0_stage18_subdone;
reg    ap_block_pp0_stage19_subdone;
reg    ap_block_pp0_stage20_subdone;
reg    ap_block_pp0_stage21_subdone;
reg    ap_block_pp0_stage22_subdone;
reg    ap_block_pp0_stage23_subdone;
reg    ap_block_pp0_stage24_subdone;
reg    ap_block_pp0_stage25_subdone;
reg    ap_block_pp0_stage26_subdone;
reg    ap_block_pp0_stage27_subdone;
reg    ap_block_pp0_stage28_subdone;
reg    ap_block_pp0_stage29_subdone;
reg    ap_block_pp0_stage30_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_1138;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 32'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 j94_fu_116 = 5'd0;
end

matrix_multiply_32x32_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage31),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage9) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_subdone))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage31) & (1'b0 == ap_block_pp0_stage31_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage9) & (ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage9_subdone)) | ((1'b1 == ap_condition_exit_pp0_iter1_stage9) & (ap_idle_pp0_0to0 == 1'b1)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage31) & (1'b0 == ap_block_pp0_stage31_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1138)) begin
        j94_fu_116 <= j_fu_1099_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage19) & (1'b0 == ap_block_pp0_stage19_11001))) begin
        gmem_b_addr_10_read_reg_1406 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_b_addr_10_reg_1220 <= add_ln60_10_fu_835_p2;
        gmem_b_addr_11_reg_1226 <= add_ln60_11_fu_847_p2;
        gmem_b_addr_12_reg_1232 <= add_ln60_12_fu_859_p2;
        gmem_b_addr_13_reg_1238 <= add_ln60_13_fu_871_p2;
        gmem_b_addr_14_reg_1244 <= add_ln60_14_fu_883_p2;
        gmem_b_addr_15_reg_1250 <= add_ln60_15_fu_895_p2;
        gmem_b_addr_16_reg_1256 <= add_ln60_16_fu_907_p2;
        gmem_b_addr_17_reg_1262 <= add_ln60_17_fu_919_p2;
        gmem_b_addr_18_reg_1268 <= add_ln60_18_fu_931_p2;
        gmem_b_addr_19_reg_1274 <= add_ln60_19_fu_943_p2;
        gmem_b_addr_1_reg_1166 <= add_ln60_1_fu_727_p2;
        gmem_b_addr_20_reg_1280 <= add_ln60_20_fu_955_p2;
        gmem_b_addr_21_reg_1286 <= add_ln60_21_fu_967_p2;
        gmem_b_addr_22_reg_1292 <= add_ln60_22_fu_979_p2;
        gmem_b_addr_23_read_reg_1471 <= m_axi_gmem_b_RDATA;
        gmem_b_addr_23_reg_1298 <= add_ln60_23_fu_991_p2;
        gmem_b_addr_24_reg_1304 <= add_ln60_24_fu_1003_p2;
        gmem_b_addr_25_reg_1310 <= add_ln60_25_fu_1015_p2;
        gmem_b_addr_26_reg_1316 <= add_ln60_26_fu_1027_p2;
        gmem_b_addr_27_reg_1322 <= add_ln60_27_fu_1039_p2;
        gmem_b_addr_28_reg_1328 <= add_ln60_28_fu_1051_p2;
        gmem_b_addr_29_reg_1334 <= add_ln60_29_fu_1063_p2;
        gmem_b_addr_2_reg_1172 <= add_ln60_2_fu_739_p2;
        gmem_b_addr_30_reg_1340 <= add_ln60_30_fu_1075_p2;
        gmem_b_addr_31_reg_1346 <= add_ln60_31_fu_1087_p2;
        gmem_b_addr_3_reg_1178 <= add_ln60_3_fu_751_p2;
        gmem_b_addr_4_reg_1184 <= add_ln60_4_fu_763_p2;
        gmem_b_addr_5_reg_1190 <= add_ln60_5_fu_775_p2;
        gmem_b_addr_6_reg_1196 <= add_ln60_6_fu_787_p2;
        gmem_b_addr_7_reg_1202 <= add_ln60_7_fu_799_p2;
        gmem_b_addr_8_reg_1208 <= add_ln60_8_fu_811_p2;
        gmem_b_addr_9_reg_1214 <= add_ln60_9_fu_823_p2;
        gmem_b_addr_reg_1160 <= add_ln60_fu_715_p2;
        icmp_ln57_reg_1352 <= icmp_ln57_fu_1105_p2;
        icmp_ln57_reg_1352_pp0_iter1_reg <= icmp_ln57_reg_1352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage20) & (1'b0 == ap_block_pp0_stage20_11001))) begin
        gmem_b_addr_11_read_reg_1411 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage21) & (1'b0 == ap_block_pp0_stage21_11001))) begin
        gmem_b_addr_12_read_reg_1416 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage22) & (1'b0 == ap_block_pp0_stage22_11001))) begin
        gmem_b_addr_13_read_reg_1421 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage23) & (1'b0 == ap_block_pp0_stage23_11001))) begin
        gmem_b_addr_14_read_reg_1426 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage24) & (1'b0 == ap_block_pp0_stage24_11001))) begin
        gmem_b_addr_15_read_reg_1431 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage25) & (1'b0 == ap_block_pp0_stage25_11001))) begin
        gmem_b_addr_16_read_reg_1436 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage26) & (1'b0 == ap_block_pp0_stage26_11001))) begin
        gmem_b_addr_17_read_reg_1441 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage27) & (1'b0 == ap_block_pp0_stage27_11001))) begin
        gmem_b_addr_18_read_reg_1446 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage28) & (1'b0 == ap_block_pp0_stage28_11001))) begin
        gmem_b_addr_19_read_reg_1451 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001))) begin
        gmem_b_addr_1_read_reg_1361 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage29) & (1'b0 == ap_block_pp0_stage29_11001))) begin
        gmem_b_addr_20_read_reg_1456 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage30) & (1'b0 == ap_block_pp0_stage30_11001))) begin
        gmem_b_addr_21_read_reg_1461 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage31) & (1'b0 == ap_block_pp0_stage31_11001))) begin
        gmem_b_addr_22_read_reg_1466 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        gmem_b_addr_24_read_reg_1476 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        gmem_b_addr_25_read_reg_1481 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        gmem_b_addr_26_read_reg_1486 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        gmem_b_addr_27_read_reg_1491 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        gmem_b_addr_28_read_reg_1496 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        gmem_b_addr_29_read_reg_1501 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11_11001))) begin
        gmem_b_addr_2_read_reg_1366 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        gmem_b_addr_30_read_reg_1506 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        gmem_b_addr_31_read_reg_1511 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12_11001))) begin
        gmem_b_addr_3_read_reg_1371 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13_11001))) begin
        gmem_b_addr_4_read_reg_1376 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14_11001))) begin
        gmem_b_addr_5_read_reg_1381 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15_11001))) begin
        gmem_b_addr_6_read_reg_1386 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage16) & (1'b0 == ap_block_pp0_stage16_11001))) begin
        gmem_b_addr_7_read_reg_1391 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage17) & (1'b0 == ap_block_pp0_stage17_11001))) begin
        gmem_b_addr_8_read_reg_1396 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage18) & (1'b0 == ap_block_pp0_stage18_11001))) begin
        gmem_b_addr_9_read_reg_1401 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001))) begin
        gmem_b_addr_read_reg_1356 <= m_axi_gmem_b_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage31) & (icmp_ln57_reg_1352 == 1'd1) & (1'b0 == ap_block_pp0_stage31_subdone))) begin
        ap_condition_exit_pp0_iter0_stage31 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage31 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln57_reg_1352_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_subdone))) begin
        ap_condition_exit_pp0_iter1_stage9 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage9 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage9) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage31) & (1'b0 == ap_block_pp0_stage31_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j94_load = 5'd0;
    end else begin
        ap_sig_allocacmp_j94_load = j94_fu_116;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9))) begin
        b_stream_blk_n = b_stream_full_n;
    end else begin
        b_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001))) begin
        b_stream_write_local = 1'b1;
    end else begin
        b_stream_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage31) & (1'b0 == ap_block_pp0_stage31)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage30) & (1'b0 == ap_block_pp0_stage30)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage29) & (1'b0 == ap_block_pp0_stage29)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage28) & (1'b0 == ap_block_pp0_stage28)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage27) & (1'b0 == ap_block_pp0_stage27)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage26) & (1'b0 == ap_block_pp0_stage26)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage25) & (1'b0 == ap_block_pp0_stage25)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage24) & (1'b0 == ap_block_pp0_stage24)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage23) & (1'b0 == ap_block_pp0_stage23)) 
    | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage22) & (1'b0 == ap_block_pp0_stage22)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage21) & (1'b0 == ap_block_pp0_stage21)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage20) & (1'b0 == ap_block_pp0_stage20)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19) & (1'b0 == ap_block_pp0_stage19)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18) & (1'b0 == ap_block_pp0_stage18)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17) & (1'b0 == ap_block_pp0_stage17)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16) & (1'b0 == ap_block_pp0_stage16)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) 
    | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) 
    | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)))) begin
        gmem_b_blk_n_AR = m_axi_gmem_b_ARREADY;
    end else begin
        gmem_b_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage31) & (1'b0 == ap_block_pp0_stage31)) 
    | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage30) & (1'b0 == ap_block_pp0_stage30)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage29) & (1'b0 == ap_block_pp0_stage29)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage28) & (1'b0 == ap_block_pp0_stage28)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage27) & (1'b0 == ap_block_pp0_stage27)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage26) & (1'b0 == ap_block_pp0_stage26)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage25) & (1'b0 == ap_block_pp0_stage25)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage24) & (1'b0 == ap_block_pp0_stage24)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage23) & (1'b0 == ap_block_pp0_stage23)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage22) & (1'b0 == ap_block_pp0_stage22)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage21) & (1'b0 == 
    ap_block_pp0_stage21)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage20) & (1'b0 == ap_block_pp0_stage20)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19) & (1'b0 == ap_block_pp0_stage19)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18) & (1'b0 == ap_block_pp0_stage18)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17) & (1'b0 == ap_block_pp0_stage17)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16) & (1'b0 == ap_block_pp0_stage16)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11) 
    & (1'b0 == ap_block_pp0_stage11)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9)))) begin
        gmem_b_blk_n_R = m_axi_gmem_b_RVALID;
    end else begin
        gmem_b_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_31_reg_1346;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage31) & (1'b0 == ap_block_pp0_stage31_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_30_reg_1340;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage30) & (1'b0 == ap_block_pp0_stage30_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_29_reg_1334;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage29) & (1'b0 == ap_block_pp0_stage29_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_28_reg_1328;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage28) & (1'b0 == ap_block_pp0_stage28_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_27_reg_1322;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage27) & (1'b0 == ap_block_pp0_stage27_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_26_reg_1316;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage26) & (1'b0 == ap_block_pp0_stage26_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_25_reg_1310;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage25) & (1'b0 == ap_block_pp0_stage25_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_24_reg_1304;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage24) & (1'b0 == ap_block_pp0_stage24_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_23_reg_1298;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage23) & (1'b0 == ap_block_pp0_stage23_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_22_reg_1292;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage22) & (1'b0 == ap_block_pp0_stage22_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_21_reg_1286;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage21) & (1'b0 == ap_block_pp0_stage21_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_20_reg_1280;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage20) & (1'b0 == ap_block_pp0_stage20_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_19_reg_1274;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19) & (1'b0 == ap_block_pp0_stage19_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_18_reg_1268;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18) & (1'b0 == ap_block_pp0_stage18_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_17_reg_1262;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17) & (1'b0 == ap_block_pp0_stage17_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_16_reg_1256;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16) & (1'b0 == ap_block_pp0_stage16_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_15_reg_1250;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_14_reg_1244;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_13_reg_1238;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_12_reg_1232;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_11_reg_1226;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_10_reg_1220;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_9_reg_1214;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_8_reg_1208;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_7_reg_1202;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_6_reg_1196;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_5_reg_1190;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_4_reg_1184;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_3_reg_1178;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_2_reg_1172;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_1_reg_1166;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_reg_1160;
    end else begin
        m_axi_gmem_b_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage31) & (1'b0 == ap_block_pp0_stage31_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage30) & (1'b0 == ap_block_pp0_stage30_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage29) & (1'b0 == ap_block_pp0_stage29_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage28) & (1'b0 == ap_block_pp0_stage28_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage27) & (1'b0 == ap_block_pp0_stage27_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage26) & (1'b0 == ap_block_pp0_stage26_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage25) & (1'b0 == ap_block_pp0_stage25_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage24) & (1'b0 == ap_block_pp0_stage24_11001)) | ((ap_enable_reg_pp0_iter0 == 
    1'b1) & (1'b1 == ap_CS_fsm_pp0_stage23) & (1'b0 == ap_block_pp0_stage23_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage22) & (1'b0 == ap_block_pp0_stage22_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage21) & (1'b0 == ap_block_pp0_stage21_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage20) & (1'b0 == ap_block_pp0_stage20_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19) & (1'b0 == ap_block_pp0_stage19_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18) & (1'b0 == ap_block_pp0_stage18_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17) & (1'b0 == ap_block_pp0_stage17_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16) & (1'b0 == ap_block_pp0_stage16_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) 
    & (1'b0 == ap_block_pp0_stage15_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) 
    | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        m_axi_gmem_b_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_b_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 
    == ap_CS_fsm_pp0_stage31) & (1'b0 == ap_block_pp0_stage31_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage30) & (1'b0 == ap_block_pp0_stage30_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage29) & (1'b0 == ap_block_pp0_stage29_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage28) & (1'b0 == ap_block_pp0_stage28_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage27) & (1'b0 == ap_block_pp0_stage27_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage26) & (1'b0 == ap_block_pp0_stage26_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage25) & (1'b0 == ap_block_pp0_stage25_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage24) & (1'b0 == ap_block_pp0_stage24_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage23) & (1'b0 == ap_block_pp0_stage23_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage22) 
    & (1'b0 == ap_block_pp0_stage22_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage21) & (1'b0 == ap_block_pp0_stage21_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage20) & (1'b0 == ap_block_pp0_stage20_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage19) & (1'b0 == ap_block_pp0_stage19_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage18) & (1'b0 == ap_block_pp0_stage18_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage17) & (1'b0 == ap_block_pp0_stage17_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16) & (1'b0 == ap_block_pp0_stage16_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13_11001)) 
    | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001)))) begin
        m_axi_gmem_b_RREADY = 1'b1;
    end else begin
        m_axi_gmem_b_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter1_stage9) & (ap_idle_pp0_0to0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        ap_ST_fsm_pp0_stage16 : begin
            if ((1'b0 == ap_block_pp0_stage16_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end
        end
        ap_ST_fsm_pp0_stage17 : begin
            if ((1'b0 == ap_block_pp0_stage17_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage17;
            end
        end
        ap_ST_fsm_pp0_stage18 : begin
            if ((1'b0 == ap_block_pp0_stage18_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage18;
            end
        end
        ap_ST_fsm_pp0_stage19 : begin
            if ((1'b0 == ap_block_pp0_stage19_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage19;
            end
        end
        ap_ST_fsm_pp0_stage20 : begin
            if ((1'b0 == ap_block_pp0_stage20_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage20;
            end
        end
        ap_ST_fsm_pp0_stage21 : begin
            if ((1'b0 == ap_block_pp0_stage21_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage21;
            end
        end
        ap_ST_fsm_pp0_stage22 : begin
            if ((1'b0 == ap_block_pp0_stage22_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage22;
            end
        end
        ap_ST_fsm_pp0_stage23 : begin
            if ((1'b0 == ap_block_pp0_stage23_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage23;
            end
        end
        ap_ST_fsm_pp0_stage24 : begin
            if ((1'b0 == ap_block_pp0_stage24_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage24;
            end
        end
        ap_ST_fsm_pp0_stage25 : begin
            if ((1'b0 == ap_block_pp0_stage25_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage25;
            end
        end
        ap_ST_fsm_pp0_stage26 : begin
            if ((1'b0 == ap_block_pp0_stage26_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage26;
            end
        end
        ap_ST_fsm_pp0_stage27 : begin
            if ((1'b0 == ap_block_pp0_stage27_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage27;
            end
        end
        ap_ST_fsm_pp0_stage28 : begin
            if ((1'b0 == ap_block_pp0_stage28_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage28;
            end
        end
        ap_ST_fsm_pp0_stage29 : begin
            if ((1'b0 == ap_block_pp0_stage29_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage29;
            end
        end
        ap_ST_fsm_pp0_stage30 : begin
            if ((1'b0 == ap_block_pp0_stage30_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage30;
            end
        end
        ap_ST_fsm_pp0_stage31 : begin
            if ((1'b0 == ap_block_pp0_stage31_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage31;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_10_fu_835_p2 = (zext_ln57_fu_711_p1 + p_read9);

assign add_ln60_11_fu_847_p2 = (zext_ln57_fu_711_p1 + p_read10);

assign add_ln60_12_fu_859_p2 = (zext_ln57_fu_711_p1 + p_read11);

assign add_ln60_13_fu_871_p2 = (zext_ln57_fu_711_p1 + p_read12);

assign add_ln60_14_fu_883_p2 = (zext_ln57_fu_711_p1 + p_read13);

assign add_ln60_15_fu_895_p2 = (zext_ln57_fu_711_p1 + p_read14);

assign add_ln60_16_fu_907_p2 = (zext_ln57_fu_711_p1 + p_read15);

assign add_ln60_17_fu_919_p2 = (zext_ln57_fu_711_p1 + p_read16);

assign add_ln60_18_fu_931_p2 = (zext_ln57_fu_711_p1 + p_read17);

assign add_ln60_19_fu_943_p2 = (zext_ln57_fu_711_p1 + p_read18);

assign add_ln60_1_fu_727_p2 = (zext_ln57_fu_711_p1 + p_read);

assign add_ln60_20_fu_955_p2 = (zext_ln57_fu_711_p1 + p_read19);

assign add_ln60_21_fu_967_p2 = (zext_ln57_fu_711_p1 + p_read20);

assign add_ln60_22_fu_979_p2 = (zext_ln57_fu_711_p1 + p_read21);

assign add_ln60_23_fu_991_p2 = (zext_ln57_fu_711_p1 + p_read22);

assign add_ln60_24_fu_1003_p2 = (zext_ln57_fu_711_p1 + p_read23);

assign add_ln60_25_fu_1015_p2 = (zext_ln57_fu_711_p1 + p_read24);

assign add_ln60_26_fu_1027_p2 = (zext_ln57_fu_711_p1 + p_read25);

assign add_ln60_27_fu_1039_p2 = (zext_ln57_fu_711_p1 + p_read26);

assign add_ln60_28_fu_1051_p2 = (zext_ln57_fu_711_p1 + p_read27);

assign add_ln60_29_fu_1063_p2 = (zext_ln57_fu_711_p1 + p_read28);

assign add_ln60_2_fu_739_p2 = (zext_ln57_fu_711_p1 + p_read1);

assign add_ln60_30_fu_1075_p2 = (zext_ln57_fu_711_p1 + p_read29);

assign add_ln60_31_fu_1087_p2 = (zext_ln57_fu_711_p1 + p_read30);

assign add_ln60_3_fu_751_p2 = (zext_ln57_fu_711_p1 + p_read2);

assign add_ln60_4_fu_763_p2 = (zext_ln57_fu_711_p1 + p_read3);

assign add_ln60_5_fu_775_p2 = (zext_ln57_fu_711_p1 + p_read4);

assign add_ln60_6_fu_787_p2 = (zext_ln57_fu_711_p1 + p_read5);

assign add_ln60_7_fu_799_p2 = (zext_ln57_fu_711_p1 + p_read6);

assign add_ln60_8_fu_811_p2 = (zext_ln57_fu_711_p1 + p_read7);

assign add_ln60_9_fu_823_p2 = (zext_ln57_fu_711_p1 + p_read8);

assign add_ln60_fu_715_p2 = (zext_ln57_fu_711_p1 + B);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage16 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp0_stage17 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_pp0_stage18 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_pp0_stage19 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage20 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_pp0_stage21 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_pp0_stage22 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_pp0_stage23 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_pp0_stage24 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_pp0_stage25 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_pp0_stage26 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_pp0_stage27 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_pp0_stage28 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_pp0_stage29 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage30 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_pp0_stage31 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state33_pp0_stage0_iter1))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state33_pp0_stage0_iter1))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage10_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state11_pp0_stage10_iter0))));
end

always @ (*) begin
    ap_block_pp0_stage10_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state11_pp0_stage10_iter0))));
end

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage11_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state12_pp0_stage11_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage11_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state12_pp0_stage11_iter0)));
end

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage12_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state13_pp0_stage12_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage12_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state13_pp0_stage12_iter0)));
end

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage13_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state14_pp0_stage13_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage13_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state14_pp0_stage13_iter0)));
end

assign ap_block_pp0_stage14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage14_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state15_pp0_stage14_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage14_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state15_pp0_stage14_iter0)));
end

assign ap_block_pp0_stage15 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage15_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state16_pp0_stage15_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage15_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state16_pp0_stage15_iter0)));
end

assign ap_block_pp0_stage16 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage16_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state17_pp0_stage16_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage16_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state17_pp0_stage16_iter0)));
end

assign ap_block_pp0_stage17 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage17_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state18_pp0_stage17_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage17_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state18_pp0_stage17_iter0)));
end

assign ap_block_pp0_stage18 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage18_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state19_pp0_stage18_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage18_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state19_pp0_stage18_iter0)));
end

assign ap_block_pp0_stage19 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage19_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state20_pp0_stage19_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage19_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state20_pp0_stage19_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state34_pp0_stage1_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state34_pp0_stage1_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage20 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage20_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state21_pp0_stage20_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage20_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state21_pp0_stage20_iter0)));
end

assign ap_block_pp0_stage21 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage21_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state22_pp0_stage21_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage21_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state22_pp0_stage21_iter0)));
end

assign ap_block_pp0_stage22 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage22_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state23_pp0_stage22_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage22_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state23_pp0_stage22_iter0)));
end

assign ap_block_pp0_stage23 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage23_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state24_pp0_stage23_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage23_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state24_pp0_stage23_iter0)));
end

assign ap_block_pp0_stage24 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage24_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state25_pp0_stage24_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage24_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state25_pp0_stage24_iter0)));
end

assign ap_block_pp0_stage25 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage25_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state26_pp0_stage25_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage25_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state26_pp0_stage25_iter0)));
end

assign ap_block_pp0_stage26 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage26_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state27_pp0_stage26_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage26_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state27_pp0_stage26_iter0)));
end

assign ap_block_pp0_stage27 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage27_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state28_pp0_stage27_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage27_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state28_pp0_stage27_iter0)));
end

assign ap_block_pp0_stage28 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage28_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state29_pp0_stage28_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage28_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state29_pp0_stage28_iter0)));
end

assign ap_block_pp0_stage29 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage29_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state30_pp0_stage29_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage29_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state30_pp0_stage29_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state35_pp0_stage2_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state35_pp0_stage2_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage30 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage30_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state31_pp0_stage30_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage30_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state31_pp0_stage30_iter0)));
end

assign ap_block_pp0_stage31 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage31_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state32_pp0_stage31_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage31_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state32_pp0_stage31_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state36_pp0_stage3_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state36_pp0_stage3_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state37_pp0_stage4_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state37_pp0_stage4_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state38_pp0_stage5_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state38_pp0_stage5_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state39_pp0_stage6_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state39_pp0_stage6_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state40_pp0_stage7_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state40_pp0_stage7_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage8_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state41_pp0_stage8_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage8_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state41_pp0_stage8_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage9_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state42_pp0_stage9_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage9_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage9_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state42_pp0_stage9_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state10_pp0_stage9_iter0))));
end

always @ (*) begin
    ap_block_pp0_stage9_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state42_pp0_stage9_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state10_pp0_stage9_iter0))));
end

always @ (*) begin
    ap_block_state10_pp0_stage9_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state11_pp0_stage10_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state12_pp0_stage11_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state13_pp0_stage12_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state14_pp0_stage13_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state15_pp0_stage14_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state16_pp0_stage15_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state17_pp0_stage16_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state18_pp0_stage17_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state19_pp0_stage18_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state20_pp0_stage19_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state21_pp0_stage20_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state22_pp0_stage21_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state23_pp0_stage22_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state24_pp0_stage23_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state25_pp0_stage24_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state26_pp0_stage25_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state27_pp0_stage26_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state28_pp0_stage27_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state29_pp0_stage28_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state30_pp0_stage29_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state31_pp0_stage30_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state32_pp0_stage31_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state33_pp0_stage0_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state34_pp0_stage1_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state35_pp0_stage2_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state36_pp0_stage3_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state37_pp0_stage4_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state38_pp0_stage5_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state39_pp0_stage6_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state40_pp0_stage7_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state41_pp0_stage8_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state42_pp0_stage9_iter1 = (b_stream_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_1138 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage31;

assign ap_ready = ap_ready_sig;

assign b_stream_din = col_b_fu_1116_p33;

assign b_stream_write = b_stream_write_local;

assign col_b_fu_1116_p33 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{gmem_b_addr_31_read_reg_1511}, {gmem_b_addr_30_read_reg_1506}}, {gmem_b_addr_29_read_reg_1501}}, {gmem_b_addr_28_read_reg_1496}}, {gmem_b_addr_27_read_reg_1491}}, {gmem_b_addr_26_read_reg_1486}}, {gmem_b_addr_25_read_reg_1481}}, {gmem_b_addr_24_read_reg_1476}}, {gmem_b_addr_23_read_reg_1471}}, {gmem_b_addr_22_read_reg_1466}}, {gmem_b_addr_21_read_reg_1461}}, {gmem_b_addr_20_read_reg_1456}}, {gmem_b_addr_19_read_reg_1451}}, {gmem_b_addr_18_read_reg_1446}}, {gmem_b_addr_17_read_reg_1441}}, {gmem_b_addr_16_read_reg_1436}}, {gmem_b_addr_15_read_reg_1431}}, {gmem_b_addr_14_read_reg_1426}}, {gmem_b_addr_13_read_reg_1421}}, {gmem_b_addr_12_read_reg_1416}}, {gmem_b_addr_11_read_reg_1411}}, {gmem_b_addr_10_read_reg_1406}}, {gmem_b_addr_9_read_reg_1401}}, {gmem_b_addr_8_read_reg_1396}}, {gmem_b_addr_7_read_reg_1391}}, {gmem_b_addr_6_read_reg_1386}}, {gmem_b_addr_5_read_reg_1381}}, {gmem_b_addr_4_read_reg_1376}}, {gmem_b_addr_3_read_reg_1371}}, {gmem_b_addr_2_read_reg_1366}}, {gmem_b_addr_1_read_reg_1361}}, 
    {gmem_b_addr_read_reg_1356}};

assign icmp_ln57_fu_1105_p2 = ((ap_sig_allocacmp_j94_load == 5'd31) ? 1'b1 : 1'b0);

assign j_fu_1099_p2 = (ap_sig_allocacmp_j94_load + 5'd1);

assign m_axi_gmem_b_ARBURST = 2'd0;

assign m_axi_gmem_b_ARCACHE = 4'd0;

assign m_axi_gmem_b_ARID = 1'd0;

assign m_axi_gmem_b_ARLEN = 64'd1;

assign m_axi_gmem_b_ARLOCK = 2'd0;

assign m_axi_gmem_b_ARPROT = 3'd0;

assign m_axi_gmem_b_ARQOS = 4'd0;

assign m_axi_gmem_b_ARREGION = 4'd0;

assign m_axi_gmem_b_ARSIZE = 3'd0;

assign m_axi_gmem_b_ARUSER = 1'd0;

assign m_axi_gmem_b_AWADDR = 64'd0;

assign m_axi_gmem_b_AWBURST = 2'd0;

assign m_axi_gmem_b_AWCACHE = 4'd0;

assign m_axi_gmem_b_AWID = 1'd0;

assign m_axi_gmem_b_AWLEN = 32'd0;

assign m_axi_gmem_b_AWLOCK = 2'd0;

assign m_axi_gmem_b_AWPROT = 3'd0;

assign m_axi_gmem_b_AWQOS = 4'd0;

assign m_axi_gmem_b_AWREGION = 4'd0;

assign m_axi_gmem_b_AWSIZE = 3'd0;

assign m_axi_gmem_b_AWUSER = 1'd0;

assign m_axi_gmem_b_AWVALID = 1'b0;

assign m_axi_gmem_b_BREADY = 1'b0;

assign m_axi_gmem_b_WDATA = 8'd0;

assign m_axi_gmem_b_WID = 1'd0;

assign m_axi_gmem_b_WLAST = 1'b0;

assign m_axi_gmem_b_WSTRB = 1'd0;

assign m_axi_gmem_b_WUSER = 1'd0;

assign m_axi_gmem_b_WVALID = 1'b0;

assign zext_ln57_fu_711_p1 = ap_sig_allocacmp_j94_load;

endmodule //matrix_multiply_32x32_Loop_VITIS_LOOP_57_3_proc
