// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matrix_multiply_16x16_Loop_VITIS_LOOP_57_3_proc2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem_b_AWVALID,
        m_axi_gmem_b_AWREADY,
        m_axi_gmem_b_AWADDR,
        m_axi_gmem_b_AWID,
        m_axi_gmem_b_AWLEN,
        m_axi_gmem_b_AWSIZE,
        m_axi_gmem_b_AWBURST,
        m_axi_gmem_b_AWLOCK,
        m_axi_gmem_b_AWCACHE,
        m_axi_gmem_b_AWPROT,
        m_axi_gmem_b_AWQOS,
        m_axi_gmem_b_AWREGION,
        m_axi_gmem_b_AWUSER,
        m_axi_gmem_b_WVALID,
        m_axi_gmem_b_WREADY,
        m_axi_gmem_b_WDATA,
        m_axi_gmem_b_WSTRB,
        m_axi_gmem_b_WLAST,
        m_axi_gmem_b_WID,
        m_axi_gmem_b_WUSER,
        m_axi_gmem_b_ARVALID,
        m_axi_gmem_b_ARREADY,
        m_axi_gmem_b_ARADDR,
        m_axi_gmem_b_ARID,
        m_axi_gmem_b_ARLEN,
        m_axi_gmem_b_ARSIZE,
        m_axi_gmem_b_ARBURST,
        m_axi_gmem_b_ARLOCK,
        m_axi_gmem_b_ARCACHE,
        m_axi_gmem_b_ARPROT,
        m_axi_gmem_b_ARQOS,
        m_axi_gmem_b_ARREGION,
        m_axi_gmem_b_ARUSER,
        m_axi_gmem_b_RVALID,
        m_axi_gmem_b_RREADY,
        m_axi_gmem_b_RDATA,
        m_axi_gmem_b_RLAST,
        m_axi_gmem_b_RID,
        m_axi_gmem_b_RFIFONUM,
        m_axi_gmem_b_RUSER,
        m_axi_gmem_b_RRESP,
        m_axi_gmem_b_BVALID,
        m_axi_gmem_b_BREADY,
        m_axi_gmem_b_BRESP,
        m_axi_gmem_b_BID,
        m_axi_gmem_b_BUSER,
        B,
        b_stream_din,
        b_stream_num_data_valid,
        b_stream_fifo_cap,
        b_stream_full_n,
        b_stream_write
);

parameter    ap_ST_fsm_pp0_stage0 = 16'd1;
parameter    ap_ST_fsm_pp0_stage1 = 16'd2;
parameter    ap_ST_fsm_pp0_stage2 = 16'd4;
parameter    ap_ST_fsm_pp0_stage3 = 16'd8;
parameter    ap_ST_fsm_pp0_stage4 = 16'd16;
parameter    ap_ST_fsm_pp0_stage5 = 16'd32;
parameter    ap_ST_fsm_pp0_stage6 = 16'd64;
parameter    ap_ST_fsm_pp0_stage7 = 16'd128;
parameter    ap_ST_fsm_pp0_stage8 = 16'd256;
parameter    ap_ST_fsm_pp0_stage9 = 16'd512;
parameter    ap_ST_fsm_pp0_stage10 = 16'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 16'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 16'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 16'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 16'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_b_AWVALID;
input   m_axi_gmem_b_AWREADY;
output  [63:0] m_axi_gmem_b_AWADDR;
output  [0:0] m_axi_gmem_b_AWID;
output  [31:0] m_axi_gmem_b_AWLEN;
output  [2:0] m_axi_gmem_b_AWSIZE;
output  [1:0] m_axi_gmem_b_AWBURST;
output  [1:0] m_axi_gmem_b_AWLOCK;
output  [3:0] m_axi_gmem_b_AWCACHE;
output  [2:0] m_axi_gmem_b_AWPROT;
output  [3:0] m_axi_gmem_b_AWQOS;
output  [3:0] m_axi_gmem_b_AWREGION;
output  [0:0] m_axi_gmem_b_AWUSER;
output   m_axi_gmem_b_WVALID;
input   m_axi_gmem_b_WREADY;
output  [7:0] m_axi_gmem_b_WDATA;
output  [0:0] m_axi_gmem_b_WSTRB;
output   m_axi_gmem_b_WLAST;
output  [0:0] m_axi_gmem_b_WID;
output  [0:0] m_axi_gmem_b_WUSER;
output   m_axi_gmem_b_ARVALID;
input   m_axi_gmem_b_ARREADY;
output  [63:0] m_axi_gmem_b_ARADDR;
output  [0:0] m_axi_gmem_b_ARID;
output  [31:0] m_axi_gmem_b_ARLEN;
output  [2:0] m_axi_gmem_b_ARSIZE;
output  [1:0] m_axi_gmem_b_ARBURST;
output  [1:0] m_axi_gmem_b_ARLOCK;
output  [3:0] m_axi_gmem_b_ARCACHE;
output  [2:0] m_axi_gmem_b_ARPROT;
output  [3:0] m_axi_gmem_b_ARQOS;
output  [3:0] m_axi_gmem_b_ARREGION;
output  [0:0] m_axi_gmem_b_ARUSER;
input   m_axi_gmem_b_RVALID;
output   m_axi_gmem_b_RREADY;
input  [7:0] m_axi_gmem_b_RDATA;
input   m_axi_gmem_b_RLAST;
input  [0:0] m_axi_gmem_b_RID;
input  [10:0] m_axi_gmem_b_RFIFONUM;
input  [0:0] m_axi_gmem_b_RUSER;
input  [1:0] m_axi_gmem_b_RRESP;
input   m_axi_gmem_b_BVALID;
output   m_axi_gmem_b_BREADY;
input  [1:0] m_axi_gmem_b_BRESP;
input  [0:0] m_axi_gmem_b_BID;
input  [0:0] m_axi_gmem_b_BUSER;
input  [63:0] B;
output  [127:0] b_stream_din;
input  [2:0] b_stream_num_data_valid;
input  [2:0] b_stream_fifo_cap;
input   b_stream_full_n;
output   b_stream_write;

reg ap_idle;
reg m_axi_gmem_b_ARVALID;
reg[63:0] m_axi_gmem_b_ARADDR;
reg m_axi_gmem_b_RREADY;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage15;
reg    ap_block_state16_pp0_stage15_iter0;
reg    ap_block_pp0_stage15_subdone;
reg   [0:0] icmp_ln57_reg_704;
reg    ap_condition_exit_pp0_iter0_stage15;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_b_blk_n_AR;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg    gmem_b_blk_n_R;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_pp0_stage13;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_pp0_stage14;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7;
wire    ap_block_pp0_stage15;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8;
wire    ap_block_pp0_stage0;
reg    b_stream_blk_n;
reg   [63:0] B_read_reg_668;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state17_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] j46_load_reg_687;
reg   [63:0] gmem_b_addr_reg_698;
wire   [0:0] icmp_ln57_fu_315_p2;
reg   [0:0] icmp_ln57_reg_704_pp0_iter1_reg;
wire  signed [4:0] zext_ln60_cast_fu_326_p3;
reg  signed [4:0] zext_ln60_cast_reg_708;
reg    ap_block_state18_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
reg   [63:0] gmem_b_addr_1_reg_715;
wire   [4:0] j46_cast_fu_348_p1;
reg   [4:0] j46_cast_reg_721;
reg    ap_block_state19_pp0_stage2_iter1;
reg    ap_block_pp0_stage2_11001;
wire  signed [5:0] zext_ln60_1_cast_fu_351_p3;
reg  signed [5:0] zext_ln60_1_cast_reg_726;
reg   [63:0] gmem_b_addr_2_reg_732;
reg   [63:0] gmem_b_addr_3_reg_738;
reg    ap_block_state20_pp0_stage3_iter1;
reg    ap_block_pp0_stage3_11001;
wire  signed [6:0] zext_ln60_3_cast_fu_395_p3;
reg  signed [6:0] zext_ln60_3_cast_reg_744;
reg    ap_block_state21_pp0_stage4_iter1;
reg    ap_block_pp0_stage4_11001;
reg   [63:0] gmem_b_addr_4_reg_749;
wire  signed [6:0] add_ln60_s_fu_418_p3;
reg  signed [6:0] add_ln60_s_reg_755;
reg    ap_block_state22_pp0_stage5_iter1;
reg    ap_block_pp0_stage5_11001;
reg   [63:0] gmem_b_addr_5_reg_760;
reg   [63:0] gmem_b_addr_6_reg_766;
reg    ap_block_state23_pp0_stage6_iter1;
reg    ap_block_pp0_stage6_11001;
reg   [63:0] gmem_b_addr_7_reg_772;
reg    ap_block_state24_pp0_stage7_iter1;
reg    ap_block_pp0_stage7_11001;
reg   [63:0] gmem_b_addr_8_reg_778;
reg   [63:0] gmem_b_addr_9_reg_784;
reg   [63:0] gmem_b_addr_10_reg_790;
reg   [63:0] gmem_b_addr_11_reg_796;
reg   [63:0] gmem_b_addr_12_reg_802;
reg   [63:0] gmem_b_addr_13_reg_808;
reg   [63:0] gmem_b_addr_14_reg_814;
reg   [63:0] gmem_b_addr_15_reg_820;
reg   [7:0] gmem_b_addr_read_reg_826;
reg    ap_block_state10_pp0_stage9_iter0;
reg    ap_block_state26_pp0_stage9_iter1;
reg    ap_block_pp0_stage9_11001;
reg   [7:0] gmem_b_addr_1_read_reg_831;
reg    ap_block_state11_pp0_stage10_iter0;
reg    ap_block_pp0_stage10_11001;
reg   [7:0] gmem_b_addr_2_read_reg_836;
reg    ap_block_state12_pp0_stage11_iter0;
reg    ap_block_pp0_stage11_11001;
reg   [7:0] gmem_b_addr_3_read_reg_841;
reg    ap_block_state13_pp0_stage12_iter0;
reg    ap_block_pp0_stage12_11001;
reg   [7:0] gmem_b_addr_4_read_reg_846;
reg    ap_block_state14_pp0_stage13_iter0;
reg    ap_block_pp0_stage13_11001;
reg   [7:0] gmem_b_addr_5_read_reg_851;
reg    ap_block_state15_pp0_stage14_iter0;
reg    ap_block_pp0_stage14_11001;
reg   [7:0] gmem_b_addr_6_read_reg_856;
reg    ap_block_pp0_stage15_11001;
reg   [7:0] gmem_b_addr_7_read_reg_861;
reg   [7:0] gmem_b_addr_8_read_reg_866;
reg   [7:0] gmem_b_addr_9_read_reg_871;
reg   [7:0] gmem_b_addr_10_read_reg_876;
reg   [7:0] gmem_b_addr_11_read_reg_881;
reg   [7:0] gmem_b_addr_12_read_reg_886;
reg   [7:0] gmem_b_addr_13_read_reg_891;
reg   [7:0] gmem_b_addr_14_read_reg_896;
reg   [7:0] gmem_b_addr_15_read_reg_901;
reg    ap_block_state25_pp0_stage8_iter1;
reg    ap_block_pp0_stage8_11001;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage9_subdone;
wire   [63:0] add_ln60_fu_297_p2;
wire   [63:0] add_ln60_1_fu_337_p2;
wire   [63:0] add_ln60_2_fu_363_p2;
wire   [63:0] add_ln60_3_fu_381_p2;
wire   [63:0] add_ln60_4_fu_407_p2;
wire   [63:0] add_ln60_5_fu_429_p2;
wire   [63:0] add_ln60_6_fu_447_p2;
wire   [63:0] add_ln60_7_fu_468_p2;
wire   [63:0] add_ln60_8_fu_491_p2;
wire   [63:0] add_ln60_9_fu_513_p2;
wire   [63:0] add_ln60_10_fu_535_p2;
wire   [63:0] add_ln60_11_fu_557_p2;
wire   [63:0] add_ln60_12_fu_575_p2;
wire   [63:0] add_ln60_13_fu_593_p2;
wire   [63:0] add_ln60_14_fu_611_p2;
wire   [63:0] add_ln60_15_fu_629_p2;
reg   [3:0] j46_fu_76;
wire   [3:0] j_fu_309_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j46_load;
wire   [127:0] col_b_fu_640_p17;
reg    ap_block_pp0_stage9_01001;
reg    b_stream_write_local;
wire   [63:0] zext_ln57_fu_293_p1;
wire   [63:0] zext_ln60_fu_333_p1;
wire   [63:0] zext_ln60_1_fu_359_p1;
wire  signed [5:0] sext_ln60_fu_374_p1;
wire   [63:0] zext_ln60_2_fu_377_p1;
wire   [5:0] zext_ln60_3_fu_392_p1;
wire   [63:0] zext_ln60_5_fu_403_p1;
wire   [63:0] zext_ln60_4_fu_425_p1;
wire  signed [6:0] sext_ln60_1_fu_440_p1;
wire   [63:0] zext_ln60_6_fu_443_p1;
wire  signed [6:0] sext_ln60_2_fu_461_p1;
wire   [63:0] zext_ln60_7_fu_464_p1;
wire   [6:0] zext_ln57_1_fu_458_p1;
wire   [7:0] zext_ln60_7_cast_fu_479_p3;
wire   [63:0] zext_ln60_9_fu_487_p1;
wire   [7:0] add_ln60_16_fu_502_p3;
wire   [63:0] zext_ln60_8_fu_509_p1;
wire   [7:0] zext_ln60_9_cast_fu_524_p3;
wire   [63:0] zext_ln60_11_fu_531_p1;
wire   [7:0] add_ln60_17_fu_546_p3;
wire   [63:0] zext_ln60_10_fu_553_p1;
wire  signed [7:0] sext_ln60_3_fu_568_p1;
wire   [63:0] zext_ln60_12_fu_571_p1;
wire  signed [7:0] sext_ln60_4_fu_586_p1;
wire   [63:0] zext_ln60_13_fu_589_p1;
wire  signed [7:0] sext_ln60_5_fu_604_p1;
wire   [63:0] zext_ln60_14_fu_607_p1;
wire  signed [7:0] sext_ln60_6_fu_622_p1;
wire   [63:0] zext_ln60_15_fu_625_p1;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage9;
reg    ap_idle_pp0_0to0;
reg   [15:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_block_pp0_stage7_subdone;
reg    ap_block_pp0_stage8_subdone;
reg    ap_block_pp0_stage10_subdone;
reg    ap_block_pp0_stage11_subdone;
reg    ap_block_pp0_stage12_subdone;
reg    ap_block_pp0_stage13_subdone;
reg    ap_block_pp0_stage14_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_642;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 j46_fu_76 = 4'd0;
end

matrix_multiply_16x16_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage15),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_subdone))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage9)) | ((1'b1 == ap_CS_fsm_pp0_stage9) & (ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage9_subdone)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_642)) begin
        j46_fu_76 <= j_fu_309_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_read_reg_668 <= B;
        gmem_b_addr_7_read_reg_861 <= m_axi_gmem_b_RDATA;
        gmem_b_addr_reg_698 <= add_ln60_fu_297_p2;
        icmp_ln57_reg_704 <= icmp_ln57_fu_315_p2;
        icmp_ln57_reg_704_pp0_iter1_reg <= icmp_ln57_reg_704;
        j46_load_reg_687 <= ap_sig_allocacmp_j46_load;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        add_ln60_s_reg_755[3 : 0] <= add_ln60_s_fu_418_p3[3 : 0];
        gmem_b_addr_12_read_reg_886 <= m_axi_gmem_b_RDATA;
        gmem_b_addr_5_reg_760 <= add_ln60_5_fu_429_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        gmem_b_addr_10_read_reg_876 <= m_axi_gmem_b_RDATA;
        gmem_b_addr_3_reg_738 <= add_ln60_3_fu_381_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        gmem_b_addr_10_reg_790 <= add_ln60_10_fu_535_p2;
        gmem_b_addr_11_reg_796 <= add_ln60_11_fu_557_p2;
        gmem_b_addr_12_reg_802 <= add_ln60_12_fu_575_p2;
        gmem_b_addr_13_reg_808 <= add_ln60_13_fu_593_p2;
        gmem_b_addr_14_read_reg_896 <= m_axi_gmem_b_RDATA;
        gmem_b_addr_14_reg_814 <= add_ln60_14_fu_611_p2;
        gmem_b_addr_15_reg_820 <= add_ln60_15_fu_629_p2;
        gmem_b_addr_7_reg_772 <= add_ln60_7_fu_468_p2;
        gmem_b_addr_8_reg_778 <= add_ln60_8_fu_491_p2;
        gmem_b_addr_9_reg_784 <= add_ln60_9_fu_513_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        gmem_b_addr_11_read_reg_881 <= m_axi_gmem_b_RDATA;
        gmem_b_addr_4_reg_749 <= add_ln60_4_fu_407_p2;
        zext_ln60_3_cast_reg_744[3 : 0] <= zext_ln60_3_cast_fu_395_p3[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        gmem_b_addr_13_read_reg_891 <= m_axi_gmem_b_RDATA;
        gmem_b_addr_6_reg_766 <= add_ln60_6_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        gmem_b_addr_15_read_reg_901 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001))) begin
        gmem_b_addr_1_read_reg_831 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        gmem_b_addr_1_reg_715 <= add_ln60_1_fu_337_p2;
        gmem_b_addr_8_read_reg_866 <= m_axi_gmem_b_RDATA;
        zext_ln60_cast_reg_708[3 : 0] <= zext_ln60_cast_fu_326_p3[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11_11001))) begin
        gmem_b_addr_2_read_reg_836 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        gmem_b_addr_2_reg_732 <= add_ln60_2_fu_363_p2;
        gmem_b_addr_9_read_reg_871 <= m_axi_gmem_b_RDATA;
        j46_cast_reg_721[3 : 0] <= j46_cast_fu_348_p1[3 : 0];
        zext_ln60_1_cast_reg_726[3 : 0] <= zext_ln60_1_cast_fu_351_p3[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12_11001))) begin
        gmem_b_addr_3_read_reg_841 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13_11001))) begin
        gmem_b_addr_4_read_reg_846 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14_11001))) begin
        gmem_b_addr_5_read_reg_851 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15_11001))) begin
        gmem_b_addr_6_read_reg_856 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001))) begin
        gmem_b_addr_read_reg_826 <= m_axi_gmem_b_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) & (icmp_ln57_reg_704 == 1'd1) & (1'b0 == ap_block_pp0_stage15_subdone))) begin
        ap_condition_exit_pp0_iter0_stage15 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage15 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln57_reg_704_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_subdone))) begin
        ap_condition_exit_pp0_iter1_stage9 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage9 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j46_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j46_load = j46_fu_76;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9))) begin
        b_stream_blk_n = b_stream_full_n;
    end else begin
        b_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001))) begin
        b_stream_write_local = 1'b1;
    end else begin
        b_stream_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) 
    | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)))) begin
        gmem_b_blk_n_AR = m_axi_gmem_b_ARREADY;
    end else begin
        gmem_b_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15)) 
    | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9)))) begin
        gmem_b_blk_n_R = m_axi_gmem_b_RVALID;
    end else begin
        gmem_b_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_15_reg_820;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_14_reg_814;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_13_reg_808;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_12_reg_802;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_11_reg_796;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_10_reg_790;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_9_reg_784;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_8_reg_778;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_7_reg_772;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_6_reg_766;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_5_reg_760;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_4_reg_749;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_3_reg_738;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_2_reg_732;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_1_reg_715;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_reg_698;
    end else begin
        m_axi_gmem_b_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) 
    & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        m_axi_gmem_b_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_b_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 
    == ap_CS_fsm_pp0_stage15) & (1'b0 == ap_block_pp0_stage15_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14) & (1'b0 == ap_block_pp0_stage14_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13) & (1'b0 == ap_block_pp0_stage13_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12) & (1'b0 == ap_block_pp0_stage12_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11) & (1'b0 == ap_block_pp0_stage11_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001)))) begin
        m_axi_gmem_b_RREADY = 1'b1;
    end else begin
        m_axi_gmem_b_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage9))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_10_fu_535_p2 = (zext_ln60_11_fu_531_p1 + B_read_reg_668);

assign add_ln60_11_fu_557_p2 = (zext_ln60_10_fu_553_p1 + B_read_reg_668);

assign add_ln60_12_fu_575_p2 = (zext_ln60_12_fu_571_p1 + B_read_reg_668);

assign add_ln60_13_fu_593_p2 = (zext_ln60_13_fu_589_p1 + B_read_reg_668);

assign add_ln60_14_fu_611_p2 = (zext_ln60_14_fu_607_p1 + B_read_reg_668);

assign add_ln60_15_fu_629_p2 = (zext_ln60_15_fu_625_p1 + B_read_reg_668);

assign add_ln60_16_fu_502_p3 = {{4'd9}, {j46_load_reg_687}};

assign add_ln60_17_fu_546_p3 = {{4'd11}, {j46_load_reg_687}};

assign add_ln60_1_fu_337_p2 = (zext_ln60_fu_333_p1 + B_read_reg_668);

assign add_ln60_2_fu_363_p2 = (zext_ln60_1_fu_359_p1 + B_read_reg_668);

assign add_ln60_3_fu_381_p2 = (zext_ln60_2_fu_377_p1 + B_read_reg_668);

assign add_ln60_4_fu_407_p2 = (zext_ln60_5_fu_403_p1 + B_read_reg_668);

assign add_ln60_5_fu_429_p2 = (zext_ln60_4_fu_425_p1 + B_read_reg_668);

assign add_ln60_6_fu_447_p2 = (zext_ln60_6_fu_443_p1 + B_read_reg_668);

assign add_ln60_7_fu_468_p2 = (zext_ln60_7_fu_464_p1 + B_read_reg_668);

assign add_ln60_8_fu_491_p2 = (zext_ln60_9_fu_487_p1 + B_read_reg_668);

assign add_ln60_9_fu_513_p2 = (zext_ln60_8_fu_509_p1 + B_read_reg_668);

assign add_ln60_fu_297_p2 = (zext_ln57_fu_293_p1 + B);

assign add_ln60_s_fu_418_p3 = {{3'd5}, {j46_load_reg_687}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state17_pp0_stage0_iter1))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state17_pp0_stage0_iter1))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage10_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state11_pp0_stage10_iter0))));
end

always @ (*) begin
    ap_block_pp0_stage10_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state11_pp0_stage10_iter0))));
end

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage11_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state12_pp0_stage11_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage11_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state12_pp0_stage11_iter0)));
end

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage12_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state13_pp0_stage12_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage12_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state13_pp0_stage12_iter0)));
end

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage13_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state14_pp0_stage13_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage13_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state14_pp0_stage13_iter0)));
end

assign ap_block_pp0_stage14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage14_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state15_pp0_stage14_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage14_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state15_pp0_stage14_iter0)));
end

assign ap_block_pp0_stage15 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage15_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state16_pp0_stage15_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage15_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state16_pp0_stage15_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage2_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage2_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state20_pp0_stage3_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state20_pp0_stage3_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state21_pp0_stage4_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state21_pp0_stage4_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage5_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage5_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage6_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage6_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state24_pp0_stage7_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state24_pp0_stage7_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage8_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state25_pp0_stage8_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage8_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state25_pp0_stage8_iter1)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage9_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state26_pp0_stage9_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage9_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage9_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state26_pp0_stage9_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state10_pp0_stage9_iter0))));
end

always @ (*) begin
    ap_block_pp0_stage9_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state26_pp0_stage9_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((m_axi_gmem_b_ARREADY == 1'b0) | (1'b1 == ap_block_state10_pp0_stage9_iter0))));
end

always @ (*) begin
    ap_block_state10_pp0_stage9_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state11_pp0_stage10_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state12_pp0_stage11_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state13_pp0_stage12_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state14_pp0_stage13_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state15_pp0_stage14_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state16_pp0_stage15_iter0 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state17_pp0_stage0_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state18_pp0_stage1_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state19_pp0_stage2_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state20_pp0_stage3_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state21_pp0_stage4_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state22_pp0_stage5_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state23_pp0_stage6_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state24_pp0_stage7_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state25_pp0_stage8_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state26_pp0_stage9_iter1 = (b_stream_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_642 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage15;

assign ap_ready = ap_ready_sig;

assign b_stream_din = col_b_fu_640_p17;

assign b_stream_write = b_stream_write_local;

assign col_b_fu_640_p17 = {{{{{{{{{{{{{{{{gmem_b_addr_15_read_reg_901}, {gmem_b_addr_14_read_reg_896}}, {gmem_b_addr_13_read_reg_891}}, {gmem_b_addr_12_read_reg_886}}, {gmem_b_addr_11_read_reg_881}}, {gmem_b_addr_10_read_reg_876}}, {gmem_b_addr_9_read_reg_871}}, {gmem_b_addr_8_read_reg_866}}, {gmem_b_addr_7_read_reg_861}}, {gmem_b_addr_6_read_reg_856}}, {gmem_b_addr_5_read_reg_851}}, {gmem_b_addr_4_read_reg_846}}, {gmem_b_addr_3_read_reg_841}}, {gmem_b_addr_2_read_reg_836}}, {gmem_b_addr_1_read_reg_831}}, {gmem_b_addr_read_reg_826}};

assign icmp_ln57_fu_315_p2 = ((ap_sig_allocacmp_j46_load == 4'd15) ? 1'b1 : 1'b0);

assign j46_cast_fu_348_p1 = j46_load_reg_687;

assign j_fu_309_p2 = (ap_sig_allocacmp_j46_load + 4'd1);

assign m_axi_gmem_b_ARBURST = 2'd0;

assign m_axi_gmem_b_ARCACHE = 4'd0;

assign m_axi_gmem_b_ARID = 1'd0;

assign m_axi_gmem_b_ARLEN = 64'd1;

assign m_axi_gmem_b_ARLOCK = 2'd0;

assign m_axi_gmem_b_ARPROT = 3'd0;

assign m_axi_gmem_b_ARQOS = 4'd0;

assign m_axi_gmem_b_ARREGION = 4'd0;

assign m_axi_gmem_b_ARSIZE = 3'd0;

assign m_axi_gmem_b_ARUSER = 1'd0;

assign m_axi_gmem_b_AWADDR = 64'd0;

assign m_axi_gmem_b_AWBURST = 2'd0;

assign m_axi_gmem_b_AWCACHE = 4'd0;

assign m_axi_gmem_b_AWID = 1'd0;

assign m_axi_gmem_b_AWLEN = 32'd0;

assign m_axi_gmem_b_AWLOCK = 2'd0;

assign m_axi_gmem_b_AWPROT = 3'd0;

assign m_axi_gmem_b_AWQOS = 4'd0;

assign m_axi_gmem_b_AWREGION = 4'd0;

assign m_axi_gmem_b_AWSIZE = 3'd0;

assign m_axi_gmem_b_AWUSER = 1'd0;

assign m_axi_gmem_b_AWVALID = 1'b0;

assign m_axi_gmem_b_BREADY = 1'b0;

assign m_axi_gmem_b_WDATA = 8'd0;

assign m_axi_gmem_b_WID = 1'd0;

assign m_axi_gmem_b_WLAST = 1'b0;

assign m_axi_gmem_b_WSTRB = 1'd0;

assign m_axi_gmem_b_WUSER = 1'd0;

assign m_axi_gmem_b_WVALID = 1'b0;

assign sext_ln60_1_fu_440_p1 = zext_ln60_1_cast_reg_726;

assign sext_ln60_2_fu_461_p1 = zext_ln60_cast_reg_708;

assign sext_ln60_3_fu_568_p1 = zext_ln60_3_cast_reg_744;

assign sext_ln60_4_fu_586_p1 = add_ln60_s_reg_755;

assign sext_ln60_5_fu_604_p1 = zext_ln60_1_cast_reg_726;

assign sext_ln60_6_fu_622_p1 = zext_ln60_cast_reg_708;

assign sext_ln60_fu_374_p1 = zext_ln60_cast_reg_708;

assign zext_ln57_1_fu_458_p1 = j46_load_reg_687;

assign zext_ln57_fu_293_p1 = ap_sig_allocacmp_j46_load;

assign zext_ln60_10_fu_553_p1 = add_ln60_17_fu_546_p3;

assign zext_ln60_11_fu_531_p1 = zext_ln60_9_cast_fu_524_p3;

assign zext_ln60_12_fu_571_p1 = $unsigned(sext_ln60_3_fu_568_p1);

assign zext_ln60_13_fu_589_p1 = $unsigned(sext_ln60_4_fu_586_p1);

assign zext_ln60_14_fu_607_p1 = $unsigned(sext_ln60_5_fu_604_p1);

assign zext_ln60_15_fu_625_p1 = $unsigned(sext_ln60_6_fu_622_p1);

assign zext_ln60_1_cast_fu_351_p3 = {{1'd1}, {j46_cast_fu_348_p1}};

assign zext_ln60_1_fu_359_p1 = $unsigned(zext_ln60_1_cast_fu_351_p3);

assign zext_ln60_2_fu_377_p1 = $unsigned(sext_ln60_fu_374_p1);

assign zext_ln60_3_cast_fu_395_p3 = {{1'd1}, {zext_ln60_3_fu_392_p1}};

assign zext_ln60_3_fu_392_p1 = j46_load_reg_687;

assign zext_ln60_4_fu_425_p1 = $unsigned(add_ln60_s_fu_418_p3);

assign zext_ln60_5_fu_403_p1 = $unsigned(zext_ln60_3_cast_fu_395_p3);

assign zext_ln60_6_fu_443_p1 = $unsigned(sext_ln60_1_fu_440_p1);

assign zext_ln60_7_cast_fu_479_p3 = {{1'd1}, {zext_ln57_1_fu_458_p1}};

assign zext_ln60_7_fu_464_p1 = $unsigned(sext_ln60_2_fu_461_p1);

assign zext_ln60_8_fu_509_p1 = add_ln60_16_fu_502_p3;

assign zext_ln60_9_cast_fu_524_p3 = {{3'd5}, {j46_cast_reg_721}};

assign zext_ln60_9_fu_487_p1 = zext_ln60_7_cast_fu_479_p3;

assign zext_ln60_cast_fu_326_p3 = {{1'd1}, {j46_load_reg_687}};

assign zext_ln60_fu_333_p1 = $unsigned(zext_ln60_cast_fu_326_p3);

always @ (posedge ap_clk) begin
    zext_ln60_cast_reg_708[4] <= 1'b1;
    j46_cast_reg_721[4] <= 1'b0;
    zext_ln60_1_cast_reg_726[5:4] <= 2'b10;
    zext_ln60_3_cast_reg_744[6:4] <= 3'b100;
    add_ln60_s_reg_755[6:4] <= 3'b101;
end

endmodule //matrix_multiply_16x16_Loop_VITIS_LOOP_57_3_proc2
