// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matrix_multiply_8x8_int8_8x8_wrapper_wrapper_1 (
        a_stream_dout,
        a_stream_empty_n,
        a_stream_read,
        b_stream_dout,
        b_stream_empty_n,
        b_stream_read,
        c_stream_din,
        c_stream_full_n,
        c_stream_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [63:0] a_stream_dout;
input   a_stream_empty_n;
output   a_stream_read;
input  [63:0] b_stream_dout;
input   b_stream_empty_n;
output   b_stream_read;
output  [127:0] c_stream_din;
input   c_stream_full_n;
output   c_stream_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    int8_8x8_wrapper_U0_ap_start;
wire    int8_8x8_wrapper_U0_ap_done;
wire    int8_8x8_wrapper_U0_ap_idle;
wire    int8_8x8_wrapper_U0_ap_ready;
wire    int8_8x8_wrapper_U0_ap_continue;
wire    int8_8x8_wrapper_U0_a_stream_read;
wire    int8_8x8_wrapper_U0_b_stream_read;
wire   [127:0] int8_8x8_wrapper_U0_c_stream_din;
wire    int8_8x8_wrapper_U0_c_stream_write;

int8_8x8_wrapper int8_8x8_wrapper_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(1'b1),
    .ap_start(int8_8x8_wrapper_U0_ap_start),
    .ap_done(int8_8x8_wrapper_U0_ap_done),
    .ap_idle(int8_8x8_wrapper_U0_ap_idle),
    .ap_ready(int8_8x8_wrapper_U0_ap_ready),
    .ap_continue(int8_8x8_wrapper_U0_ap_continue),
    .a_tdata(a_stream_dout),
    .a_tready(a_stream_empty_n),
    .a_tvalid(int8_8x8_wrapper_U0_a_stream_read),
    .b_tdata(b_stream_dout),
    .b_tready(b_stream_empty_n),
    .b_tvalid(int8_8x8_wrapper_U0_b_stream_read),
    .c_tdata(int8_8x8_wrapper_U0_c_stream_din),
    .c_tready(c_stream_full_n),
    .c_tvalid(int8_8x8_wrapper_U0_c_stream_write)
);

assign a_stream_read = int8_8x8_wrapper_U0_a_stream_read;

assign ap_done = int8_8x8_wrapper_U0_ap_done;

assign ap_idle = int8_8x8_wrapper_U0_ap_idle;

assign ap_ready = int8_8x8_wrapper_U0_ap_ready;

assign b_stream_read = int8_8x8_wrapper_U0_b_stream_read;

assign c_stream_din = int8_8x8_wrapper_U0_c_stream_din;

assign c_stream_write = int8_8x8_wrapper_U0_c_stream_write;

assign int8_8x8_wrapper_U0_ap_continue = ap_continue;

assign int8_8x8_wrapper_U0_ap_start = ap_start;

endmodule //matrix_multiply_8x8_int8_8x8_wrapper_wrapper_1
