// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_multiply_8x8_matrix_multiply_8x8,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=91,HLS_SYN_TPT=64,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=3746,HLS_SYN_LUT=4696,HLS_VERSION=2024_1}" *)

module matrix_multiply_8x8 (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem_a_AWVALID,
        m_axi_gmem_a_AWREADY,
        m_axi_gmem_a_AWADDR,
        m_axi_gmem_a_AWID,
        m_axi_gmem_a_AWLEN,
        m_axi_gmem_a_AWSIZE,
        m_axi_gmem_a_AWBURST,
        m_axi_gmem_a_AWLOCK,
        m_axi_gmem_a_AWCACHE,
        m_axi_gmem_a_AWPROT,
        m_axi_gmem_a_AWQOS,
        m_axi_gmem_a_AWREGION,
        m_axi_gmem_a_AWUSER,
        m_axi_gmem_a_WVALID,
        m_axi_gmem_a_WREADY,
        m_axi_gmem_a_WDATA,
        m_axi_gmem_a_WSTRB,
        m_axi_gmem_a_WLAST,
        m_axi_gmem_a_WID,
        m_axi_gmem_a_WUSER,
        m_axi_gmem_a_ARVALID,
        m_axi_gmem_a_ARREADY,
        m_axi_gmem_a_ARADDR,
        m_axi_gmem_a_ARID,
        m_axi_gmem_a_ARLEN,
        m_axi_gmem_a_ARSIZE,
        m_axi_gmem_a_ARBURST,
        m_axi_gmem_a_ARLOCK,
        m_axi_gmem_a_ARCACHE,
        m_axi_gmem_a_ARPROT,
        m_axi_gmem_a_ARQOS,
        m_axi_gmem_a_ARREGION,
        m_axi_gmem_a_ARUSER,
        m_axi_gmem_a_RVALID,
        m_axi_gmem_a_RREADY,
        m_axi_gmem_a_RDATA,
        m_axi_gmem_a_RLAST,
        m_axi_gmem_a_RID,
        m_axi_gmem_a_RUSER,
        m_axi_gmem_a_RRESP,
        m_axi_gmem_a_BVALID,
        m_axi_gmem_a_BREADY,
        m_axi_gmem_a_BRESP,
        m_axi_gmem_a_BID,
        m_axi_gmem_a_BUSER,
        m_axi_gmem_b_AWVALID,
        m_axi_gmem_b_AWREADY,
        m_axi_gmem_b_AWADDR,
        m_axi_gmem_b_AWID,
        m_axi_gmem_b_AWLEN,
        m_axi_gmem_b_AWSIZE,
        m_axi_gmem_b_AWBURST,
        m_axi_gmem_b_AWLOCK,
        m_axi_gmem_b_AWCACHE,
        m_axi_gmem_b_AWPROT,
        m_axi_gmem_b_AWQOS,
        m_axi_gmem_b_AWREGION,
        m_axi_gmem_b_AWUSER,
        m_axi_gmem_b_WVALID,
        m_axi_gmem_b_WREADY,
        m_axi_gmem_b_WDATA,
        m_axi_gmem_b_WSTRB,
        m_axi_gmem_b_WLAST,
        m_axi_gmem_b_WID,
        m_axi_gmem_b_WUSER,
        m_axi_gmem_b_ARVALID,
        m_axi_gmem_b_ARREADY,
        m_axi_gmem_b_ARADDR,
        m_axi_gmem_b_ARID,
        m_axi_gmem_b_ARLEN,
        m_axi_gmem_b_ARSIZE,
        m_axi_gmem_b_ARBURST,
        m_axi_gmem_b_ARLOCK,
        m_axi_gmem_b_ARCACHE,
        m_axi_gmem_b_ARPROT,
        m_axi_gmem_b_ARQOS,
        m_axi_gmem_b_ARREGION,
        m_axi_gmem_b_ARUSER,
        m_axi_gmem_b_RVALID,
        m_axi_gmem_b_RREADY,
        m_axi_gmem_b_RDATA,
        m_axi_gmem_b_RLAST,
        m_axi_gmem_b_RID,
        m_axi_gmem_b_RUSER,
        m_axi_gmem_b_RRESP,
        m_axi_gmem_b_BVALID,
        m_axi_gmem_b_BREADY,
        m_axi_gmem_b_BRESP,
        m_axi_gmem_b_BID,
        m_axi_gmem_b_BUSER,
        m_axi_gmem_c_AWVALID,
        m_axi_gmem_c_AWREADY,
        m_axi_gmem_c_AWADDR,
        m_axi_gmem_c_AWID,
        m_axi_gmem_c_AWLEN,
        m_axi_gmem_c_AWSIZE,
        m_axi_gmem_c_AWBURST,
        m_axi_gmem_c_AWLOCK,
        m_axi_gmem_c_AWCACHE,
        m_axi_gmem_c_AWPROT,
        m_axi_gmem_c_AWQOS,
        m_axi_gmem_c_AWREGION,
        m_axi_gmem_c_AWUSER,
        m_axi_gmem_c_WVALID,
        m_axi_gmem_c_WREADY,
        m_axi_gmem_c_WDATA,
        m_axi_gmem_c_WSTRB,
        m_axi_gmem_c_WLAST,
        m_axi_gmem_c_WID,
        m_axi_gmem_c_WUSER,
        m_axi_gmem_c_ARVALID,
        m_axi_gmem_c_ARREADY,
        m_axi_gmem_c_ARADDR,
        m_axi_gmem_c_ARID,
        m_axi_gmem_c_ARLEN,
        m_axi_gmem_c_ARSIZE,
        m_axi_gmem_c_ARBURST,
        m_axi_gmem_c_ARLOCK,
        m_axi_gmem_c_ARCACHE,
        m_axi_gmem_c_ARPROT,
        m_axi_gmem_c_ARQOS,
        m_axi_gmem_c_ARREGION,
        m_axi_gmem_c_ARUSER,
        m_axi_gmem_c_RVALID,
        m_axi_gmem_c_RREADY,
        m_axi_gmem_c_RDATA,
        m_axi_gmem_c_RLAST,
        m_axi_gmem_c_RID,
        m_axi_gmem_c_RUSER,
        m_axi_gmem_c_RRESP,
        m_axi_gmem_c_BVALID,
        m_axi_gmem_c_BREADY,
        m_axi_gmem_c_BRESP,
        m_axi_gmem_c_BID,
        m_axi_gmem_c_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_A_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_A_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_A_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_A_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_A_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_A_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_A_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_A_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_A_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_A_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_A_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_B_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_B_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_B_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_B_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_B_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_B_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_B_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_B_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_B_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_B_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_B_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM_C_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_C_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_C_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_C_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_C_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_C_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_C_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_C_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_C_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_C_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_C_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_A_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_B_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_C_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem_a_AWVALID;
input   m_axi_gmem_a_AWREADY;
output  [C_M_AXI_GMEM_A_ADDR_WIDTH - 1:0] m_axi_gmem_a_AWADDR;
output  [C_M_AXI_GMEM_A_ID_WIDTH - 1:0] m_axi_gmem_a_AWID;
output  [7:0] m_axi_gmem_a_AWLEN;
output  [2:0] m_axi_gmem_a_AWSIZE;
output  [1:0] m_axi_gmem_a_AWBURST;
output  [1:0] m_axi_gmem_a_AWLOCK;
output  [3:0] m_axi_gmem_a_AWCACHE;
output  [2:0] m_axi_gmem_a_AWPROT;
output  [3:0] m_axi_gmem_a_AWQOS;
output  [3:0] m_axi_gmem_a_AWREGION;
output  [C_M_AXI_GMEM_A_AWUSER_WIDTH - 1:0] m_axi_gmem_a_AWUSER;
output   m_axi_gmem_a_WVALID;
input   m_axi_gmem_a_WREADY;
output  [C_M_AXI_GMEM_A_DATA_WIDTH - 1:0] m_axi_gmem_a_WDATA;
output  [C_M_AXI_GMEM_A_WSTRB_WIDTH - 1:0] m_axi_gmem_a_WSTRB;
output   m_axi_gmem_a_WLAST;
output  [C_M_AXI_GMEM_A_ID_WIDTH - 1:0] m_axi_gmem_a_WID;
output  [C_M_AXI_GMEM_A_WUSER_WIDTH - 1:0] m_axi_gmem_a_WUSER;
output   m_axi_gmem_a_ARVALID;
input   m_axi_gmem_a_ARREADY;
output  [C_M_AXI_GMEM_A_ADDR_WIDTH - 1:0] m_axi_gmem_a_ARADDR;
output  [C_M_AXI_GMEM_A_ID_WIDTH - 1:0] m_axi_gmem_a_ARID;
output  [7:0] m_axi_gmem_a_ARLEN;
output  [2:0] m_axi_gmem_a_ARSIZE;
output  [1:0] m_axi_gmem_a_ARBURST;
output  [1:0] m_axi_gmem_a_ARLOCK;
output  [3:0] m_axi_gmem_a_ARCACHE;
output  [2:0] m_axi_gmem_a_ARPROT;
output  [3:0] m_axi_gmem_a_ARQOS;
output  [3:0] m_axi_gmem_a_ARREGION;
output  [C_M_AXI_GMEM_A_ARUSER_WIDTH - 1:0] m_axi_gmem_a_ARUSER;
input   m_axi_gmem_a_RVALID;
output   m_axi_gmem_a_RREADY;
input  [C_M_AXI_GMEM_A_DATA_WIDTH - 1:0] m_axi_gmem_a_RDATA;
input   m_axi_gmem_a_RLAST;
input  [C_M_AXI_GMEM_A_ID_WIDTH - 1:0] m_axi_gmem_a_RID;
input  [C_M_AXI_GMEM_A_RUSER_WIDTH - 1:0] m_axi_gmem_a_RUSER;
input  [1:0] m_axi_gmem_a_RRESP;
input   m_axi_gmem_a_BVALID;
output   m_axi_gmem_a_BREADY;
input  [1:0] m_axi_gmem_a_BRESP;
input  [C_M_AXI_GMEM_A_ID_WIDTH - 1:0] m_axi_gmem_a_BID;
input  [C_M_AXI_GMEM_A_BUSER_WIDTH - 1:0] m_axi_gmem_a_BUSER;
output   m_axi_gmem_b_AWVALID;
input   m_axi_gmem_b_AWREADY;
output  [C_M_AXI_GMEM_B_ADDR_WIDTH - 1:0] m_axi_gmem_b_AWADDR;
output  [C_M_AXI_GMEM_B_ID_WIDTH - 1:0] m_axi_gmem_b_AWID;
output  [7:0] m_axi_gmem_b_AWLEN;
output  [2:0] m_axi_gmem_b_AWSIZE;
output  [1:0] m_axi_gmem_b_AWBURST;
output  [1:0] m_axi_gmem_b_AWLOCK;
output  [3:0] m_axi_gmem_b_AWCACHE;
output  [2:0] m_axi_gmem_b_AWPROT;
output  [3:0] m_axi_gmem_b_AWQOS;
output  [3:0] m_axi_gmem_b_AWREGION;
output  [C_M_AXI_GMEM_B_AWUSER_WIDTH - 1:0] m_axi_gmem_b_AWUSER;
output   m_axi_gmem_b_WVALID;
input   m_axi_gmem_b_WREADY;
output  [C_M_AXI_GMEM_B_DATA_WIDTH - 1:0] m_axi_gmem_b_WDATA;
output  [C_M_AXI_GMEM_B_WSTRB_WIDTH - 1:0] m_axi_gmem_b_WSTRB;
output   m_axi_gmem_b_WLAST;
output  [C_M_AXI_GMEM_B_ID_WIDTH - 1:0] m_axi_gmem_b_WID;
output  [C_M_AXI_GMEM_B_WUSER_WIDTH - 1:0] m_axi_gmem_b_WUSER;
output   m_axi_gmem_b_ARVALID;
input   m_axi_gmem_b_ARREADY;
output  [C_M_AXI_GMEM_B_ADDR_WIDTH - 1:0] m_axi_gmem_b_ARADDR;
output  [C_M_AXI_GMEM_B_ID_WIDTH - 1:0] m_axi_gmem_b_ARID;
output  [7:0] m_axi_gmem_b_ARLEN;
output  [2:0] m_axi_gmem_b_ARSIZE;
output  [1:0] m_axi_gmem_b_ARBURST;
output  [1:0] m_axi_gmem_b_ARLOCK;
output  [3:0] m_axi_gmem_b_ARCACHE;
output  [2:0] m_axi_gmem_b_ARPROT;
output  [3:0] m_axi_gmem_b_ARQOS;
output  [3:0] m_axi_gmem_b_ARREGION;
output  [C_M_AXI_GMEM_B_ARUSER_WIDTH - 1:0] m_axi_gmem_b_ARUSER;
input   m_axi_gmem_b_RVALID;
output   m_axi_gmem_b_RREADY;
input  [C_M_AXI_GMEM_B_DATA_WIDTH - 1:0] m_axi_gmem_b_RDATA;
input   m_axi_gmem_b_RLAST;
input  [C_M_AXI_GMEM_B_ID_WIDTH - 1:0] m_axi_gmem_b_RID;
input  [C_M_AXI_GMEM_B_RUSER_WIDTH - 1:0] m_axi_gmem_b_RUSER;
input  [1:0] m_axi_gmem_b_RRESP;
input   m_axi_gmem_b_BVALID;
output   m_axi_gmem_b_BREADY;
input  [1:0] m_axi_gmem_b_BRESP;
input  [C_M_AXI_GMEM_B_ID_WIDTH - 1:0] m_axi_gmem_b_BID;
input  [C_M_AXI_GMEM_B_BUSER_WIDTH - 1:0] m_axi_gmem_b_BUSER;
output   m_axi_gmem_c_AWVALID;
input   m_axi_gmem_c_AWREADY;
output  [C_M_AXI_GMEM_C_ADDR_WIDTH - 1:0] m_axi_gmem_c_AWADDR;
output  [C_M_AXI_GMEM_C_ID_WIDTH - 1:0] m_axi_gmem_c_AWID;
output  [7:0] m_axi_gmem_c_AWLEN;
output  [2:0] m_axi_gmem_c_AWSIZE;
output  [1:0] m_axi_gmem_c_AWBURST;
output  [1:0] m_axi_gmem_c_AWLOCK;
output  [3:0] m_axi_gmem_c_AWCACHE;
output  [2:0] m_axi_gmem_c_AWPROT;
output  [3:0] m_axi_gmem_c_AWQOS;
output  [3:0] m_axi_gmem_c_AWREGION;
output  [C_M_AXI_GMEM_C_AWUSER_WIDTH - 1:0] m_axi_gmem_c_AWUSER;
output   m_axi_gmem_c_WVALID;
input   m_axi_gmem_c_WREADY;
output  [C_M_AXI_GMEM_C_DATA_WIDTH - 1:0] m_axi_gmem_c_WDATA;
output  [C_M_AXI_GMEM_C_WSTRB_WIDTH - 1:0] m_axi_gmem_c_WSTRB;
output   m_axi_gmem_c_WLAST;
output  [C_M_AXI_GMEM_C_ID_WIDTH - 1:0] m_axi_gmem_c_WID;
output  [C_M_AXI_GMEM_C_WUSER_WIDTH - 1:0] m_axi_gmem_c_WUSER;
output   m_axi_gmem_c_ARVALID;
input   m_axi_gmem_c_ARREADY;
output  [C_M_AXI_GMEM_C_ADDR_WIDTH - 1:0] m_axi_gmem_c_ARADDR;
output  [C_M_AXI_GMEM_C_ID_WIDTH - 1:0] m_axi_gmem_c_ARID;
output  [7:0] m_axi_gmem_c_ARLEN;
output  [2:0] m_axi_gmem_c_ARSIZE;
output  [1:0] m_axi_gmem_c_ARBURST;
output  [1:0] m_axi_gmem_c_ARLOCK;
output  [3:0] m_axi_gmem_c_ARCACHE;
output  [2:0] m_axi_gmem_c_ARPROT;
output  [3:0] m_axi_gmem_c_ARQOS;
output  [3:0] m_axi_gmem_c_ARREGION;
output  [C_M_AXI_GMEM_C_ARUSER_WIDTH - 1:0] m_axi_gmem_c_ARUSER;
input   m_axi_gmem_c_RVALID;
output   m_axi_gmem_c_RREADY;
input  [C_M_AXI_GMEM_C_DATA_WIDTH - 1:0] m_axi_gmem_c_RDATA;
input   m_axi_gmem_c_RLAST;
input  [C_M_AXI_GMEM_C_ID_WIDTH - 1:0] m_axi_gmem_c_RID;
input  [C_M_AXI_GMEM_C_RUSER_WIDTH - 1:0] m_axi_gmem_c_RUSER;
input  [1:0] m_axi_gmem_c_RRESP;
input   m_axi_gmem_c_BVALID;
output   m_axi_gmem_c_BREADY;
input  [1:0] m_axi_gmem_c_BRESP;
input  [C_M_AXI_GMEM_C_ID_WIDTH - 1:0] m_axi_gmem_c_BID;
input  [C_M_AXI_GMEM_C_BUSER_WIDTH - 1:0] m_axi_gmem_c_BUSER;

 reg    ap_rst_n_inv;
wire   [63:0] A;
wire   [63:0] B;
wire   [63:0] C;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    gmem_a_AWREADY;
wire    gmem_a_WREADY;
wire    gmem_a_ARREADY;
wire    gmem_a_RVALID;
wire   [7:0] gmem_a_RDATA;
wire    gmem_a_RLAST;
wire   [0:0] gmem_a_RID;
wire   [10:0] gmem_a_RFIFONUM;
wire   [0:0] gmem_a_RUSER;
wire   [1:0] gmem_a_RRESP;
wire    gmem_a_BVALID;
wire    gmem_b_AWREADY;
wire    gmem_b_WREADY;
wire    gmem_b_ARREADY;
wire    gmem_b_RVALID;
wire   [7:0] gmem_b_RDATA;
wire    gmem_b_RLAST;
wire   [0:0] gmem_b_RID;
wire   [10:0] gmem_b_RFIFONUM;
wire   [0:0] gmem_b_RUSER;
wire   [1:0] gmem_b_RRESP;
wire    gmem_b_BVALID;
wire    gmem_c_AWREADY;
wire    gmem_c_WREADY;
wire    gmem_c_ARREADY;
wire    gmem_c_RVALID;
wire   [15:0] gmem_c_RDATA;
wire   [9:0] gmem_c_RFIFONUM;
wire    gmem_c_BVALID;
wire   [1:0] gmem_c_BRESP;
wire   [0:0] gmem_c_BID;
wire   [0:0] gmem_c_BUSER;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_C_c_din;
wire    entry_proc_U0_C_c_write;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_ap_start;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_ap_done;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_ap_continue;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_ap_idle;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWVALID;
wire   [63:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWID;
wire   [31:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWUSER;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WVALID;
wire   [7:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WDATA;
wire   [0:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WSTRB;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WLAST;
wire   [0:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WID;
wire   [0:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WUSER;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARVALID;
wire   [63:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARID;
wire   [31:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARUSER;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_RREADY;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_BREADY;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_start_out;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_start_write;
wire   [63:0] Loop_VITIS_LOOP_45_1_proc1_U0_a_stream_din;
wire    Loop_VITIS_LOOP_45_1_proc1_U0_a_stream_write;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_ap_start;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_ap_done;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_ap_continue;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_ap_idle;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWVALID;
wire   [63:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWID;
wire   [31:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWUSER;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WVALID;
wire   [7:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WDATA;
wire   [0:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WSTRB;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WLAST;
wire   [0:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WID;
wire   [0:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WUSER;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARVALID;
wire   [63:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARID;
wire   [31:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARUSER;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_RREADY;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_BREADY;
wire   [63:0] Loop_VITIS_LOOP_55_3_proc2_U0_b_stream_din;
wire    Loop_VITIS_LOOP_55_3_proc2_U0_b_stream_write;
wire    int8_8x8_wrapper_wrapper_1_U0_a_stream_read;
wire    int8_8x8_wrapper_wrapper_1_U0_b_stream_read;
wire   [127:0] int8_8x8_wrapper_wrapper_1_U0_c_stream_din;
wire    int8_8x8_wrapper_wrapper_1_U0_c_stream_write;
wire    int8_8x8_wrapper_wrapper_1_U0_ap_start;
wire    int8_8x8_wrapper_wrapper_1_U0_ap_done;
wire    int8_8x8_wrapper_wrapper_1_U0_ap_ready;
wire    int8_8x8_wrapper_wrapper_1_U0_ap_idle;
wire    int8_8x8_wrapper_wrapper_1_U0_ap_continue;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_ap_start;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_ap_done;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_ap_continue;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_ap_idle;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_ap_ready;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_C_read;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_c_stream_read;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWVALID;
wire   [63:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWID;
wire   [31:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWUSER;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WVALID;
wire   [15:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WDATA;
wire   [1:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WSTRB;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WLAST;
wire   [0:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WID;
wire   [0:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WUSER;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARVALID;
wire   [63:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARID;
wire   [31:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARUSER;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_RREADY;
wire    Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_BREADY;
wire    C_c_full_n;
wire   [63:0] C_c_dout;
wire   [2:0] C_c_num_data_valid;
wire   [2:0] C_c_fifo_cap;
wire    C_c_empty_n;
wire    a_stream_full_n;
wire   [63:0] a_stream_dout;
wire   [2:0] a_stream_num_data_valid;
wire   [2:0] a_stream_fifo_cap;
wire    a_stream_empty_n;
wire    b_stream_full_n;
wire   [63:0] b_stream_dout;
wire   [2:0] b_stream_num_data_valid;
wire   [2:0] b_stream_fifo_cap;
wire    b_stream_empty_n;
wire    c_stream_full_n;
wire   [127:0] c_stream_dout;
wire   [2:0] c_stream_num_data_valid;
wire   [2:0] c_stream_fifo_cap;
wire    c_stream_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready;
wire    ap_sync_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready;
reg    ap_sync_reg_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready;
wire    ap_sync_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready;
wire   [0:0] start_for_Loop_VITIS_LOOP_68_5_proc3_U0_din;
wire    start_for_Loop_VITIS_LOOP_68_5_proc3_U0_full_n;
wire   [0:0] start_for_Loop_VITIS_LOOP_68_5_proc3_U0_dout;
wire    start_for_Loop_VITIS_LOOP_68_5_proc3_U0_empty_n;
wire   [0:0] start_for_int8_8x8_wrapper_wrapper_1_U0_din;
wire    start_for_int8_8x8_wrapper_wrapper_1_U0_full_n;
wire   [0:0] start_for_int8_8x8_wrapper_wrapper_1_U0_dout;
wire    start_for_int8_8x8_wrapper_wrapper_1_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready = 1'b0;
end

matrix_multiply_8x8_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .A(A),
    .B(B),
    .C(C),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

matrix_multiply_8x8_gmem_a_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_A_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_A_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_A_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_A_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_A_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_A_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_A_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_A_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_A_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_A_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_A_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 8 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_a_m_axi_U(
    .AWVALID(m_axi_gmem_a_AWVALID),
    .AWREADY(m_axi_gmem_a_AWREADY),
    .AWADDR(m_axi_gmem_a_AWADDR),
    .AWID(m_axi_gmem_a_AWID),
    .AWLEN(m_axi_gmem_a_AWLEN),
    .AWSIZE(m_axi_gmem_a_AWSIZE),
    .AWBURST(m_axi_gmem_a_AWBURST),
    .AWLOCK(m_axi_gmem_a_AWLOCK),
    .AWCACHE(m_axi_gmem_a_AWCACHE),
    .AWPROT(m_axi_gmem_a_AWPROT),
    .AWQOS(m_axi_gmem_a_AWQOS),
    .AWREGION(m_axi_gmem_a_AWREGION),
    .AWUSER(m_axi_gmem_a_AWUSER),
    .WVALID(m_axi_gmem_a_WVALID),
    .WREADY(m_axi_gmem_a_WREADY),
    .WDATA(m_axi_gmem_a_WDATA),
    .WSTRB(m_axi_gmem_a_WSTRB),
    .WLAST(m_axi_gmem_a_WLAST),
    .WID(m_axi_gmem_a_WID),
    .WUSER(m_axi_gmem_a_WUSER),
    .ARVALID(m_axi_gmem_a_ARVALID),
    .ARREADY(m_axi_gmem_a_ARREADY),
    .ARADDR(m_axi_gmem_a_ARADDR),
    .ARID(m_axi_gmem_a_ARID),
    .ARLEN(m_axi_gmem_a_ARLEN),
    .ARSIZE(m_axi_gmem_a_ARSIZE),
    .ARBURST(m_axi_gmem_a_ARBURST),
    .ARLOCK(m_axi_gmem_a_ARLOCK),
    .ARCACHE(m_axi_gmem_a_ARCACHE),
    .ARPROT(m_axi_gmem_a_ARPROT),
    .ARQOS(m_axi_gmem_a_ARQOS),
    .ARREGION(m_axi_gmem_a_ARREGION),
    .ARUSER(m_axi_gmem_a_ARUSER),
    .RVALID(m_axi_gmem_a_RVALID),
    .RREADY(m_axi_gmem_a_RREADY),
    .RDATA(m_axi_gmem_a_RDATA),
    .RLAST(m_axi_gmem_a_RLAST),
    .RID(m_axi_gmem_a_RID),
    .RUSER(m_axi_gmem_a_RUSER),
    .RRESP(m_axi_gmem_a_RRESP),
    .BVALID(m_axi_gmem_a_BVALID),
    .BREADY(m_axi_gmem_a_BREADY),
    .BRESP(m_axi_gmem_a_BRESP),
    .BID(m_axi_gmem_a_BID),
    .BUSER(m_axi_gmem_a_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARVALID),
    .I_CH0_ARREADY(gmem_a_ARREADY),
    .I_CH0_ARADDR(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARADDR),
    .I_CH0_ARLEN(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARLEN),
    .I_CH0_RVALID(gmem_a_RVALID),
    .I_CH0_RREADY(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_RREADY),
    .I_CH0_RDATA(gmem_a_RDATA),
    .I_CH0_RFIFONUM(gmem_a_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_a_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_a_WREADY),
    .I_CH0_WDATA(8'd0),
    .I_CH0_WSTRB(1'd0),
    .I_CH0_BVALID(gmem_a_BVALID),
    .I_CH0_BREADY(1'b0)
);

matrix_multiply_8x8_gmem_b_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_B_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_B_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_B_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_B_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_B_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_B_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_B_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_B_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_B_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_B_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_B_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 8 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_b_m_axi_U(
    .AWVALID(m_axi_gmem_b_AWVALID),
    .AWREADY(m_axi_gmem_b_AWREADY),
    .AWADDR(m_axi_gmem_b_AWADDR),
    .AWID(m_axi_gmem_b_AWID),
    .AWLEN(m_axi_gmem_b_AWLEN),
    .AWSIZE(m_axi_gmem_b_AWSIZE),
    .AWBURST(m_axi_gmem_b_AWBURST),
    .AWLOCK(m_axi_gmem_b_AWLOCK),
    .AWCACHE(m_axi_gmem_b_AWCACHE),
    .AWPROT(m_axi_gmem_b_AWPROT),
    .AWQOS(m_axi_gmem_b_AWQOS),
    .AWREGION(m_axi_gmem_b_AWREGION),
    .AWUSER(m_axi_gmem_b_AWUSER),
    .WVALID(m_axi_gmem_b_WVALID),
    .WREADY(m_axi_gmem_b_WREADY),
    .WDATA(m_axi_gmem_b_WDATA),
    .WSTRB(m_axi_gmem_b_WSTRB),
    .WLAST(m_axi_gmem_b_WLAST),
    .WID(m_axi_gmem_b_WID),
    .WUSER(m_axi_gmem_b_WUSER),
    .ARVALID(m_axi_gmem_b_ARVALID),
    .ARREADY(m_axi_gmem_b_ARREADY),
    .ARADDR(m_axi_gmem_b_ARADDR),
    .ARID(m_axi_gmem_b_ARID),
    .ARLEN(m_axi_gmem_b_ARLEN),
    .ARSIZE(m_axi_gmem_b_ARSIZE),
    .ARBURST(m_axi_gmem_b_ARBURST),
    .ARLOCK(m_axi_gmem_b_ARLOCK),
    .ARCACHE(m_axi_gmem_b_ARCACHE),
    .ARPROT(m_axi_gmem_b_ARPROT),
    .ARQOS(m_axi_gmem_b_ARQOS),
    .ARREGION(m_axi_gmem_b_ARREGION),
    .ARUSER(m_axi_gmem_b_ARUSER),
    .RVALID(m_axi_gmem_b_RVALID),
    .RREADY(m_axi_gmem_b_RREADY),
    .RDATA(m_axi_gmem_b_RDATA),
    .RLAST(m_axi_gmem_b_RLAST),
    .RID(m_axi_gmem_b_RID),
    .RUSER(m_axi_gmem_b_RUSER),
    .RRESP(m_axi_gmem_b_RRESP),
    .BVALID(m_axi_gmem_b_BVALID),
    .BREADY(m_axi_gmem_b_BREADY),
    .BRESP(m_axi_gmem_b_BRESP),
    .BID(m_axi_gmem_b_BID),
    .BUSER(m_axi_gmem_b_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARVALID),
    .I_CH0_ARREADY(gmem_b_ARREADY),
    .I_CH0_ARADDR(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARADDR),
    .I_CH0_ARLEN(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARLEN),
    .I_CH0_RVALID(gmem_b_RVALID),
    .I_CH0_RREADY(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_RREADY),
    .I_CH0_RDATA(gmem_b_RDATA),
    .I_CH0_RFIFONUM(gmem_b_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_b_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_b_WREADY),
    .I_CH0_WDATA(8'd0),
    .I_CH0_WSTRB(1'd0),
    .I_CH0_BVALID(gmem_b_BVALID),
    .I_CH0_BREADY(1'b0)
);

matrix_multiply_8x8_gmem_c_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_C_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_C_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_C_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_C_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_C_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_C_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_C_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_C_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_C_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_C_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_C_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_c_m_axi_U(
    .AWVALID(m_axi_gmem_c_AWVALID),
    .AWREADY(m_axi_gmem_c_AWREADY),
    .AWADDR(m_axi_gmem_c_AWADDR),
    .AWID(m_axi_gmem_c_AWID),
    .AWLEN(m_axi_gmem_c_AWLEN),
    .AWSIZE(m_axi_gmem_c_AWSIZE),
    .AWBURST(m_axi_gmem_c_AWBURST),
    .AWLOCK(m_axi_gmem_c_AWLOCK),
    .AWCACHE(m_axi_gmem_c_AWCACHE),
    .AWPROT(m_axi_gmem_c_AWPROT),
    .AWQOS(m_axi_gmem_c_AWQOS),
    .AWREGION(m_axi_gmem_c_AWREGION),
    .AWUSER(m_axi_gmem_c_AWUSER),
    .WVALID(m_axi_gmem_c_WVALID),
    .WREADY(m_axi_gmem_c_WREADY),
    .WDATA(m_axi_gmem_c_WDATA),
    .WSTRB(m_axi_gmem_c_WSTRB),
    .WLAST(m_axi_gmem_c_WLAST),
    .WID(m_axi_gmem_c_WID),
    .WUSER(m_axi_gmem_c_WUSER),
    .ARVALID(m_axi_gmem_c_ARVALID),
    .ARREADY(m_axi_gmem_c_ARREADY),
    .ARADDR(m_axi_gmem_c_ARADDR),
    .ARID(m_axi_gmem_c_ARID),
    .ARLEN(m_axi_gmem_c_ARLEN),
    .ARSIZE(m_axi_gmem_c_ARSIZE),
    .ARBURST(m_axi_gmem_c_ARBURST),
    .ARLOCK(m_axi_gmem_c_ARLOCK),
    .ARCACHE(m_axi_gmem_c_ARCACHE),
    .ARPROT(m_axi_gmem_c_ARPROT),
    .ARQOS(m_axi_gmem_c_ARQOS),
    .ARREGION(m_axi_gmem_c_ARREGION),
    .ARUSER(m_axi_gmem_c_ARUSER),
    .RVALID(m_axi_gmem_c_RVALID),
    .RREADY(m_axi_gmem_c_RREADY),
    .RDATA(m_axi_gmem_c_RDATA),
    .RLAST(m_axi_gmem_c_RLAST),
    .RID(m_axi_gmem_c_RID),
    .RUSER(m_axi_gmem_c_RUSER),
    .RRESP(m_axi_gmem_c_RRESP),
    .BVALID(m_axi_gmem_c_BVALID),
    .BREADY(m_axi_gmem_c_BREADY),
    .BRESP(m_axi_gmem_c_BRESP),
    .BID(m_axi_gmem_c_BID),
    .BUSER(m_axi_gmem_c_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem_c_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem_c_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem_c_RDATA),
    .I_CH0_RFIFONUM(gmem_c_RFIFONUM),
    .I_CH0_AWVALID(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWVALID),
    .I_CH0_AWREADY(gmem_c_AWREADY),
    .I_CH0_AWADDR(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWADDR),
    .I_CH0_AWLEN(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWLEN),
    .I_CH0_WVALID(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WVALID),
    .I_CH0_WREADY(gmem_c_WREADY),
    .I_CH0_WDATA(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WDATA),
    .I_CH0_WSTRB(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WSTRB),
    .I_CH0_BVALID(gmem_c_BVALID),
    .I_CH0_BREADY(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_BREADY)
);

matrix_multiply_8x8_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_Loop_VITIS_LOOP_68_5_proc3_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .C(C),
    .C_c_din(entry_proc_U0_C_c_din),
    .C_c_num_data_valid(C_c_num_data_valid),
    .C_c_fifo_cap(C_c_fifo_cap),
    .C_c_full_n(C_c_full_n),
    .C_c_write(entry_proc_U0_C_c_write)
);

matrix_multiply_8x8_Loop_VITIS_LOOP_45_1_proc1 Loop_VITIS_LOOP_45_1_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_45_1_proc1_U0_ap_start),
    .start_full_n(start_for_int8_8x8_wrapper_wrapper_1_U0_full_n),
    .ap_done(Loop_VITIS_LOOP_45_1_proc1_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_45_1_proc1_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_45_1_proc1_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready),
    .m_axi_gmem_a_AWVALID(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWVALID),
    .m_axi_gmem_a_AWREADY(1'b0),
    .m_axi_gmem_a_AWADDR(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWADDR),
    .m_axi_gmem_a_AWID(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWID),
    .m_axi_gmem_a_AWLEN(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWLEN),
    .m_axi_gmem_a_AWSIZE(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWSIZE),
    .m_axi_gmem_a_AWBURST(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWBURST),
    .m_axi_gmem_a_AWLOCK(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWLOCK),
    .m_axi_gmem_a_AWCACHE(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWCACHE),
    .m_axi_gmem_a_AWPROT(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWPROT),
    .m_axi_gmem_a_AWQOS(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWQOS),
    .m_axi_gmem_a_AWREGION(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWREGION),
    .m_axi_gmem_a_AWUSER(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_AWUSER),
    .m_axi_gmem_a_WVALID(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WVALID),
    .m_axi_gmem_a_WREADY(1'b0),
    .m_axi_gmem_a_WDATA(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WDATA),
    .m_axi_gmem_a_WSTRB(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WSTRB),
    .m_axi_gmem_a_WLAST(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WLAST),
    .m_axi_gmem_a_WID(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WID),
    .m_axi_gmem_a_WUSER(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_WUSER),
    .m_axi_gmem_a_ARVALID(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARVALID),
    .m_axi_gmem_a_ARREADY(gmem_a_ARREADY),
    .m_axi_gmem_a_ARADDR(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARADDR),
    .m_axi_gmem_a_ARID(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARID),
    .m_axi_gmem_a_ARLEN(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARLEN),
    .m_axi_gmem_a_ARSIZE(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARSIZE),
    .m_axi_gmem_a_ARBURST(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARBURST),
    .m_axi_gmem_a_ARLOCK(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARLOCK),
    .m_axi_gmem_a_ARCACHE(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARCACHE),
    .m_axi_gmem_a_ARPROT(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARPROT),
    .m_axi_gmem_a_ARQOS(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARQOS),
    .m_axi_gmem_a_ARREGION(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARREGION),
    .m_axi_gmem_a_ARUSER(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_ARUSER),
    .m_axi_gmem_a_RVALID(gmem_a_RVALID),
    .m_axi_gmem_a_RREADY(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_RREADY),
    .m_axi_gmem_a_RDATA(gmem_a_RDATA),
    .m_axi_gmem_a_RLAST(gmem_a_RLAST),
    .m_axi_gmem_a_RID(gmem_a_RID),
    .m_axi_gmem_a_RFIFONUM(gmem_a_RFIFONUM),
    .m_axi_gmem_a_RUSER(gmem_a_RUSER),
    .m_axi_gmem_a_RRESP(gmem_a_RRESP),
    .m_axi_gmem_a_BVALID(1'b0),
    .m_axi_gmem_a_BREADY(Loop_VITIS_LOOP_45_1_proc1_U0_m_axi_gmem_a_BREADY),
    .m_axi_gmem_a_BRESP(2'd0),
    .m_axi_gmem_a_BID(1'd0),
    .m_axi_gmem_a_BUSER(1'd0),
    .start_out(Loop_VITIS_LOOP_45_1_proc1_U0_start_out),
    .start_write(Loop_VITIS_LOOP_45_1_proc1_U0_start_write),
    .A(A),
    .a_stream_din(Loop_VITIS_LOOP_45_1_proc1_U0_a_stream_din),
    .a_stream_num_data_valid(a_stream_num_data_valid),
    .a_stream_fifo_cap(a_stream_fifo_cap),
    .a_stream_full_n(a_stream_full_n),
    .a_stream_write(Loop_VITIS_LOOP_45_1_proc1_U0_a_stream_write)
);

matrix_multiply_8x8_Loop_VITIS_LOOP_55_3_proc2 Loop_VITIS_LOOP_55_3_proc2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_55_3_proc2_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_55_3_proc2_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_55_3_proc2_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_55_3_proc2_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready),
    .m_axi_gmem_b_AWVALID(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWVALID),
    .m_axi_gmem_b_AWREADY(1'b0),
    .m_axi_gmem_b_AWADDR(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWADDR),
    .m_axi_gmem_b_AWID(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWID),
    .m_axi_gmem_b_AWLEN(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWLEN),
    .m_axi_gmem_b_AWSIZE(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWSIZE),
    .m_axi_gmem_b_AWBURST(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWBURST),
    .m_axi_gmem_b_AWLOCK(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWLOCK),
    .m_axi_gmem_b_AWCACHE(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWCACHE),
    .m_axi_gmem_b_AWPROT(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWPROT),
    .m_axi_gmem_b_AWQOS(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWQOS),
    .m_axi_gmem_b_AWREGION(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWREGION),
    .m_axi_gmem_b_AWUSER(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_AWUSER),
    .m_axi_gmem_b_WVALID(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WVALID),
    .m_axi_gmem_b_WREADY(1'b0),
    .m_axi_gmem_b_WDATA(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WDATA),
    .m_axi_gmem_b_WSTRB(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WSTRB),
    .m_axi_gmem_b_WLAST(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WLAST),
    .m_axi_gmem_b_WID(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WID),
    .m_axi_gmem_b_WUSER(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_WUSER),
    .m_axi_gmem_b_ARVALID(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARVALID),
    .m_axi_gmem_b_ARREADY(gmem_b_ARREADY),
    .m_axi_gmem_b_ARADDR(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARADDR),
    .m_axi_gmem_b_ARID(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARID),
    .m_axi_gmem_b_ARLEN(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARLEN),
    .m_axi_gmem_b_ARSIZE(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARSIZE),
    .m_axi_gmem_b_ARBURST(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARBURST),
    .m_axi_gmem_b_ARLOCK(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARLOCK),
    .m_axi_gmem_b_ARCACHE(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARCACHE),
    .m_axi_gmem_b_ARPROT(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARPROT),
    .m_axi_gmem_b_ARQOS(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARQOS),
    .m_axi_gmem_b_ARREGION(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARREGION),
    .m_axi_gmem_b_ARUSER(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_ARUSER),
    .m_axi_gmem_b_RVALID(gmem_b_RVALID),
    .m_axi_gmem_b_RREADY(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_RREADY),
    .m_axi_gmem_b_RDATA(gmem_b_RDATA),
    .m_axi_gmem_b_RLAST(gmem_b_RLAST),
    .m_axi_gmem_b_RID(gmem_b_RID),
    .m_axi_gmem_b_RFIFONUM(gmem_b_RFIFONUM),
    .m_axi_gmem_b_RUSER(gmem_b_RUSER),
    .m_axi_gmem_b_RRESP(gmem_b_RRESP),
    .m_axi_gmem_b_BVALID(1'b0),
    .m_axi_gmem_b_BREADY(Loop_VITIS_LOOP_55_3_proc2_U0_m_axi_gmem_b_BREADY),
    .m_axi_gmem_b_BRESP(2'd0),
    .m_axi_gmem_b_BID(1'd0),
    .m_axi_gmem_b_BUSER(1'd0),
    .B(B),
    .b_stream_din(Loop_VITIS_LOOP_55_3_proc2_U0_b_stream_din),
    .b_stream_num_data_valid(b_stream_num_data_valid),
    .b_stream_fifo_cap(b_stream_fifo_cap),
    .b_stream_full_n(b_stream_full_n),
    .b_stream_write(Loop_VITIS_LOOP_55_3_proc2_U0_b_stream_write)
);

matrix_multiply_8x8_int8_8x8_wrapper_wrapper_1 int8_8x8_wrapper_wrapper_1_U0(
    .a_stream_dout(a_stream_dout),
    .a_stream_empty_n(a_stream_empty_n),
    .a_stream_read(int8_8x8_wrapper_wrapper_1_U0_a_stream_read),
    .b_stream_dout(b_stream_dout),
    .b_stream_empty_n(b_stream_empty_n),
    .b_stream_read(int8_8x8_wrapper_wrapper_1_U0_b_stream_read),
    .c_stream_din(int8_8x8_wrapper_wrapper_1_U0_c_stream_din),
    .c_stream_full_n(c_stream_full_n),
    .c_stream_write(int8_8x8_wrapper_wrapper_1_U0_c_stream_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(int8_8x8_wrapper_wrapper_1_U0_ap_start),
    .ap_done(int8_8x8_wrapper_wrapper_1_U0_ap_done),
    .ap_ready(int8_8x8_wrapper_wrapper_1_U0_ap_ready),
    .ap_idle(int8_8x8_wrapper_wrapper_1_U0_ap_idle),
    .ap_continue(int8_8x8_wrapper_wrapper_1_U0_ap_continue)
);

matrix_multiply_8x8_Loop_VITIS_LOOP_68_5_proc3 Loop_VITIS_LOOP_68_5_proc3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_68_5_proc3_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_68_5_proc3_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_68_5_proc3_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_68_5_proc3_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_68_5_proc3_U0_ap_ready),
    .C_dout(C_c_dout),
    .C_num_data_valid(C_c_num_data_valid),
    .C_fifo_cap(C_c_fifo_cap),
    .C_empty_n(C_c_empty_n),
    .C_read(Loop_VITIS_LOOP_68_5_proc3_U0_C_read),
    .c_stream_dout(c_stream_dout),
    .c_stream_num_data_valid(c_stream_num_data_valid),
    .c_stream_fifo_cap(c_stream_fifo_cap),
    .c_stream_empty_n(c_stream_empty_n),
    .c_stream_read(Loop_VITIS_LOOP_68_5_proc3_U0_c_stream_read),
    .m_axi_gmem_c_AWVALID(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWVALID),
    .m_axi_gmem_c_AWREADY(gmem_c_AWREADY),
    .m_axi_gmem_c_AWADDR(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWADDR),
    .m_axi_gmem_c_AWID(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWID),
    .m_axi_gmem_c_AWLEN(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWLEN),
    .m_axi_gmem_c_AWSIZE(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWSIZE),
    .m_axi_gmem_c_AWBURST(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWBURST),
    .m_axi_gmem_c_AWLOCK(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWLOCK),
    .m_axi_gmem_c_AWCACHE(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWCACHE),
    .m_axi_gmem_c_AWPROT(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWPROT),
    .m_axi_gmem_c_AWQOS(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWQOS),
    .m_axi_gmem_c_AWREGION(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWREGION),
    .m_axi_gmem_c_AWUSER(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_AWUSER),
    .m_axi_gmem_c_WVALID(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WVALID),
    .m_axi_gmem_c_WREADY(gmem_c_WREADY),
    .m_axi_gmem_c_WDATA(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WDATA),
    .m_axi_gmem_c_WSTRB(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WSTRB),
    .m_axi_gmem_c_WLAST(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WLAST),
    .m_axi_gmem_c_WID(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WID),
    .m_axi_gmem_c_WUSER(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_WUSER),
    .m_axi_gmem_c_ARVALID(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARVALID),
    .m_axi_gmem_c_ARREADY(1'b0),
    .m_axi_gmem_c_ARADDR(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARADDR),
    .m_axi_gmem_c_ARID(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARID),
    .m_axi_gmem_c_ARLEN(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARLEN),
    .m_axi_gmem_c_ARSIZE(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARSIZE),
    .m_axi_gmem_c_ARBURST(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARBURST),
    .m_axi_gmem_c_ARLOCK(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARLOCK),
    .m_axi_gmem_c_ARCACHE(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARCACHE),
    .m_axi_gmem_c_ARPROT(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARPROT),
    .m_axi_gmem_c_ARQOS(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARQOS),
    .m_axi_gmem_c_ARREGION(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARREGION),
    .m_axi_gmem_c_ARUSER(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_ARUSER),
    .m_axi_gmem_c_RVALID(1'b0),
    .m_axi_gmem_c_RREADY(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_RREADY),
    .m_axi_gmem_c_RDATA(16'd0),
    .m_axi_gmem_c_RLAST(1'b0),
    .m_axi_gmem_c_RID(1'd0),
    .m_axi_gmem_c_RFIFONUM(10'd0),
    .m_axi_gmem_c_RUSER(1'd0),
    .m_axi_gmem_c_RRESP(2'd0),
    .m_axi_gmem_c_BVALID(gmem_c_BVALID),
    .m_axi_gmem_c_BREADY(Loop_VITIS_LOOP_68_5_proc3_U0_m_axi_gmem_c_BREADY),
    .m_axi_gmem_c_BRESP(gmem_c_BRESP),
    .m_axi_gmem_c_BID(gmem_c_BID),
    .m_axi_gmem_c_BUSER(gmem_c_BUSER)
);

matrix_multiply_8x8_fifo_w64_d4_S C_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_C_c_din),
    .if_full_n(C_c_full_n),
    .if_write(entry_proc_U0_C_c_write),
    .if_dout(C_c_dout),
    .if_num_data_valid(C_c_num_data_valid),
    .if_fifo_cap(C_c_fifo_cap),
    .if_empty_n(C_c_empty_n),
    .if_read(Loop_VITIS_LOOP_68_5_proc3_U0_C_read)
);

matrix_multiply_8x8_fifo_w64_d2_S a_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_45_1_proc1_U0_a_stream_din),
    .if_full_n(a_stream_full_n),
    .if_write(Loop_VITIS_LOOP_45_1_proc1_U0_a_stream_write),
    .if_dout(a_stream_dout),
    .if_num_data_valid(a_stream_num_data_valid),
    .if_fifo_cap(a_stream_fifo_cap),
    .if_empty_n(a_stream_empty_n),
    .if_read(int8_8x8_wrapper_wrapper_1_U0_a_stream_read)
);

matrix_multiply_8x8_fifo_w64_d2_S b_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_55_3_proc2_U0_b_stream_din),
    .if_full_n(b_stream_full_n),
    .if_write(Loop_VITIS_LOOP_55_3_proc2_U0_b_stream_write),
    .if_dout(b_stream_dout),
    .if_num_data_valid(b_stream_num_data_valid),
    .if_fifo_cap(b_stream_fifo_cap),
    .if_empty_n(b_stream_empty_n),
    .if_read(int8_8x8_wrapper_wrapper_1_U0_b_stream_read)
);

matrix_multiply_8x8_fifo_w128_d2_S c_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(int8_8x8_wrapper_wrapper_1_U0_c_stream_din),
    .if_full_n(c_stream_full_n),
    .if_write(int8_8x8_wrapper_wrapper_1_U0_c_stream_write),
    .if_dout(c_stream_dout),
    .if_num_data_valid(c_stream_num_data_valid),
    .if_fifo_cap(c_stream_fifo_cap),
    .if_empty_n(c_stream_empty_n),
    .if_read(Loop_VITIS_LOOP_68_5_proc3_U0_c_stream_read)
);

matrix_multiply_8x8_start_for_Loop_VITIS_LOOP_68_5_proc3_U0 start_for_Loop_VITIS_LOOP_68_5_proc3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_VITIS_LOOP_68_5_proc3_U0_din),
    .if_full_n(start_for_Loop_VITIS_LOOP_68_5_proc3_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_Loop_VITIS_LOOP_68_5_proc3_U0_dout),
    .if_empty_n(start_for_Loop_VITIS_LOOP_68_5_proc3_U0_empty_n),
    .if_read(Loop_VITIS_LOOP_68_5_proc3_U0_ap_ready)
);

matrix_multiply_8x8_start_for_int8_8x8_wrapper_wrapper_1_U0 start_for_int8_8x8_wrapper_wrapper_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_int8_8x8_wrapper_wrapper_1_U0_din),
    .if_full_n(start_for_int8_8x8_wrapper_wrapper_1_U0_full_n),
    .if_write(Loop_VITIS_LOOP_45_1_proc1_U0_start_write),
    .if_dout(start_for_int8_8x8_wrapper_wrapper_1_U0_dout),
    .if_empty_n(start_for_int8_8x8_wrapper_wrapper_1_U0_empty_n),
    .if_read(int8_8x8_wrapper_wrapper_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready <= ap_sync_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready <= ap_sync_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign Loop_VITIS_LOOP_45_1_proc1_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_45_1_proc1_U0_ap_start = ((ap_sync_reg_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready ^ 1'b1) & ap_start);

assign Loop_VITIS_LOOP_55_3_proc2_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_55_3_proc2_U0_ap_start = ((ap_sync_reg_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready ^ 1'b1) & ap_start);

assign Loop_VITIS_LOOP_68_5_proc3_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_68_5_proc3_U0_ap_start = start_for_Loop_VITIS_LOOP_68_5_proc3_U0_empty_n;

assign ap_done = Loop_VITIS_LOOP_68_5_proc3_U0_ap_done;

assign ap_idle = (int8_8x8_wrapper_wrapper_1_U0_ap_idle & entry_proc_U0_ap_idle & Loop_VITIS_LOOP_68_5_proc3_U0_ap_idle & Loop_VITIS_LOOP_55_3_proc2_U0_ap_idle & Loop_VITIS_LOOP_45_1_proc1_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready = (ap_sync_reg_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready | Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready);

assign ap_sync_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready = (ap_sync_reg_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready | Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_Loop_VITIS_LOOP_55_3_proc2_U0_ap_ready & ap_sync_Loop_VITIS_LOOP_45_1_proc1_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign gmem_a_RID = 1'd0;

assign gmem_a_RLAST = 1'b0;

assign gmem_a_RRESP = 2'd0;

assign gmem_a_RUSER = 1'd0;

assign gmem_b_RID = 1'd0;

assign gmem_b_RLAST = 1'b0;

assign gmem_b_RRESP = 2'd0;

assign gmem_b_RUSER = 1'd0;

assign gmem_c_BID = 1'd0;

assign gmem_c_BRESP = 2'd0;

assign gmem_c_BUSER = 1'd0;

assign int8_8x8_wrapper_wrapper_1_U0_ap_continue = 1'b1;

assign int8_8x8_wrapper_wrapper_1_U0_ap_start = start_for_int8_8x8_wrapper_wrapper_1_U0_empty_n;

assign start_for_Loop_VITIS_LOOP_68_5_proc3_U0_din = 1'b1;

assign start_for_int8_8x8_wrapper_wrapper_1_U0_din = 1'b1;

endmodule //matrix_multiply_8x8
