// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matrix_multiply_8x8_Loop_VITIS_LOOP_68_5_proc3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        C_dout,
        C_num_data_valid,
        C_fifo_cap,
        C_empty_n,
        C_read,
        c_stream_dout,
        c_stream_num_data_valid,
        c_stream_fifo_cap,
        c_stream_empty_n,
        c_stream_read,
        m_axi_gmem_c_AWVALID,
        m_axi_gmem_c_AWREADY,
        m_axi_gmem_c_AWADDR,
        m_axi_gmem_c_AWID,
        m_axi_gmem_c_AWLEN,
        m_axi_gmem_c_AWSIZE,
        m_axi_gmem_c_AWBURST,
        m_axi_gmem_c_AWLOCK,
        m_axi_gmem_c_AWCACHE,
        m_axi_gmem_c_AWPROT,
        m_axi_gmem_c_AWQOS,
        m_axi_gmem_c_AWREGION,
        m_axi_gmem_c_AWUSER,
        m_axi_gmem_c_WVALID,
        m_axi_gmem_c_WREADY,
        m_axi_gmem_c_WDATA,
        m_axi_gmem_c_WSTRB,
        m_axi_gmem_c_WLAST,
        m_axi_gmem_c_WID,
        m_axi_gmem_c_WUSER,
        m_axi_gmem_c_ARVALID,
        m_axi_gmem_c_ARREADY,
        m_axi_gmem_c_ARADDR,
        m_axi_gmem_c_ARID,
        m_axi_gmem_c_ARLEN,
        m_axi_gmem_c_ARSIZE,
        m_axi_gmem_c_ARBURST,
        m_axi_gmem_c_ARLOCK,
        m_axi_gmem_c_ARCACHE,
        m_axi_gmem_c_ARPROT,
        m_axi_gmem_c_ARQOS,
        m_axi_gmem_c_ARREGION,
        m_axi_gmem_c_ARUSER,
        m_axi_gmem_c_RVALID,
        m_axi_gmem_c_RREADY,
        m_axi_gmem_c_RDATA,
        m_axi_gmem_c_RLAST,
        m_axi_gmem_c_RID,
        m_axi_gmem_c_RFIFONUM,
        m_axi_gmem_c_RUSER,
        m_axi_gmem_c_RRESP,
        m_axi_gmem_c_BVALID,
        m_axi_gmem_c_BREADY,
        m_axi_gmem_c_BRESP,
        m_axi_gmem_c_BID,
        m_axi_gmem_c_BUSER
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] C_dout;
input  [2:0] C_num_data_valid;
input  [2:0] C_fifo_cap;
input   C_empty_n;
output   C_read;
input  [127:0] c_stream_dout;
input  [2:0] c_stream_num_data_valid;
input  [2:0] c_stream_fifo_cap;
input   c_stream_empty_n;
output   c_stream_read;
output   m_axi_gmem_c_AWVALID;
input   m_axi_gmem_c_AWREADY;
output  [63:0] m_axi_gmem_c_AWADDR;
output  [0:0] m_axi_gmem_c_AWID;
output  [31:0] m_axi_gmem_c_AWLEN;
output  [2:0] m_axi_gmem_c_AWSIZE;
output  [1:0] m_axi_gmem_c_AWBURST;
output  [1:0] m_axi_gmem_c_AWLOCK;
output  [3:0] m_axi_gmem_c_AWCACHE;
output  [2:0] m_axi_gmem_c_AWPROT;
output  [3:0] m_axi_gmem_c_AWQOS;
output  [3:0] m_axi_gmem_c_AWREGION;
output  [0:0] m_axi_gmem_c_AWUSER;
output   m_axi_gmem_c_WVALID;
input   m_axi_gmem_c_WREADY;
output  [15:0] m_axi_gmem_c_WDATA;
output  [1:0] m_axi_gmem_c_WSTRB;
output   m_axi_gmem_c_WLAST;
output  [0:0] m_axi_gmem_c_WID;
output  [0:0] m_axi_gmem_c_WUSER;
output   m_axi_gmem_c_ARVALID;
input   m_axi_gmem_c_ARREADY;
output  [63:0] m_axi_gmem_c_ARADDR;
output  [0:0] m_axi_gmem_c_ARID;
output  [31:0] m_axi_gmem_c_ARLEN;
output  [2:0] m_axi_gmem_c_ARSIZE;
output  [1:0] m_axi_gmem_c_ARBURST;
output  [1:0] m_axi_gmem_c_ARLOCK;
output  [3:0] m_axi_gmem_c_ARCACHE;
output  [2:0] m_axi_gmem_c_ARPROT;
output  [3:0] m_axi_gmem_c_ARQOS;
output  [3:0] m_axi_gmem_c_ARREGION;
output  [0:0] m_axi_gmem_c_ARUSER;
input   m_axi_gmem_c_RVALID;
output   m_axi_gmem_c_RREADY;
input  [15:0] m_axi_gmem_c_RDATA;
input   m_axi_gmem_c_RLAST;
input  [0:0] m_axi_gmem_c_RID;
input  [9:0] m_axi_gmem_c_RFIFONUM;
input  [0:0] m_axi_gmem_c_RUSER;
input  [1:0] m_axi_gmem_c_RRESP;
input   m_axi_gmem_c_BVALID;
output   m_axi_gmem_c_BREADY;
input  [1:0] m_axi_gmem_c_BRESP;
input  [0:0] m_axi_gmem_c_BID;
input  [0:0] m_axi_gmem_c_BUSER;

reg ap_idle;
reg m_axi_gmem_c_AWVALID;
reg m_axi_gmem_c_WVALID;
reg m_axi_gmem_c_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] first_iter_08_reg_126;
reg   [0:0] first_iter_0_reg_309;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] first_iter_08_reg_126_pp0_iter1_reg;
reg    ap_block_state3_io;
reg   [0:0] icmp_ln68_reg_323;
reg   [0:0] icmp_ln68_reg_323_pp0_iter7_reg;
reg    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln68_fu_203_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    C_blk_n;
wire    ap_block_pp0_stage0;
reg    gmem_c_blk_n_AW;
reg    gmem_c_blk_n_W;
reg    gmem_c_blk_n_B;
reg    c_stream_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] first_iter_0_fu_172_p2;
wire   [2:0] trunc_ln71_fu_187_p1;
reg   [2:0] trunc_ln71_reg_313;
reg   [2:0] trunc_ln71_reg_313_pp0_iter1_reg;
wire   [0:0] icmp_ln70_fu_197_p2;
reg   [0:0] icmp_ln70_reg_318;
reg   [0:0] icmp_ln68_reg_323_pp0_iter1_reg;
reg   [0:0] icmp_ln68_reg_323_pp0_iter2_reg;
reg   [0:0] icmp_ln68_reg_323_pp0_iter3_reg;
reg   [0:0] icmp_ln68_reg_323_pp0_iter4_reg;
reg   [0:0] icmp_ln68_reg_323_pp0_iter5_reg;
reg   [0:0] icmp_ln68_reg_323_pp0_iter6_reg;
reg   [63:0] gmem_c_addr_reg_327;
wire   [15:0] trunc_ln71_1_fu_272_p1;
reg   [15:0] trunc_ln71_1_reg_332;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_icmp_ln707_phi_fu_141_p4;
wire  signed [63:0] sext_ln68_fu_229_p1;
reg    ap_block_pp0_stage0_01001;
reg   [5:0] indvar_flatten4_fu_78;
wire   [5:0] add_ln68_fu_178_p2;
reg   [5:0] ap_sig_allocacmp_indvar_flatten4_load;
reg   [5:0] ap_sig_allocacmp_indvar_flatten4_load_1;
reg   [3:0] j6_fu_82;
wire   [3:0] j_fu_191_p2;
reg   [3:0] ap_sig_allocacmp_j6_load;
reg   [127:0] row_c15_fu_86;
reg    C_read_local;
reg    c_stream_read_local;
wire   [3:0] select_ln68_fu_164_p3;
wire   [62:0] trunc_ln_fu_219_p4;
wire   [6:0] shl_ln_fu_255_p3;
wire   [127:0] zext_ln71_fu_262_p1;
wire   [127:0] lshr_ln71_fu_266_p2;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_395;
reg    ap_condition_400;
reg    ap_condition_217;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 indvar_flatten4_fu_78 = 6'd0;
#0 j6_fu_82 = 4'd0;
#0 row_c15_fu_86 = 128'd0;
end

matrix_multiply_8x8_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_400)) begin
            first_iter_08_reg_126 <= 1'd0;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            first_iter_08_reg_126 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_217)) begin
        indvar_flatten4_fu_78 <= add_ln68_fu_178_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_217)) begin
    j6_fu_82 <= j_fu_191_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        first_iter_08_reg_126_pp0_iter1_reg <= first_iter_08_reg_126;
        first_iter_0_reg_309 <= first_iter_0_fu_172_p2;
        gmem_c_addr_reg_327 <= sext_ln68_fu_229_p1;
        icmp_ln68_reg_323 <= icmp_ln68_fu_203_p2;
        icmp_ln68_reg_323_pp0_iter1_reg <= icmp_ln68_reg_323;
        trunc_ln71_reg_313 <= trunc_ln71_fu_187_p1;
        trunc_ln71_reg_313_pp0_iter1_reg <= trunc_ln71_reg_313;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        icmp_ln68_reg_323_pp0_iter2_reg <= icmp_ln68_reg_323_pp0_iter1_reg;
        icmp_ln68_reg_323_pp0_iter3_reg <= icmp_ln68_reg_323_pp0_iter2_reg;
        icmp_ln68_reg_323_pp0_iter4_reg <= icmp_ln68_reg_323_pp0_iter3_reg;
        icmp_ln68_reg_323_pp0_iter5_reg <= icmp_ln68_reg_323_pp0_iter4_reg;
        icmp_ln68_reg_323_pp0_iter6_reg <= icmp_ln68_reg_323_pp0_iter5_reg;
        icmp_ln68_reg_323_pp0_iter7_reg <= icmp_ln68_reg_323_pp0_iter6_reg;
        trunc_ln71_1_reg_332 <= trunc_ln71_1_fu_272_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln70_reg_318 <= icmp_ln70_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((first_iter_0_reg_309 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        row_c15_fu_86 <= c_stream_dout;
    end
end

always @ (*) begin
    if (((first_iter_08_reg_126 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        C_blk_n = C_empty_n;
    end else begin
        C_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((first_iter_08_reg_126 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        C_read_local = 1'b1;
    end else begin
        C_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln68_fu_203_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_395)) begin
            ap_phi_mux_icmp_ln707_phi_fu_141_p4 = icmp_ln70_reg_318;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln707_phi_fu_141_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln707_phi_fu_141_p4 = icmp_ln70_reg_318;
        end
    end else begin
        ap_phi_mux_icmp_ln707_phi_fu_141_p4 = icmp_ln70_reg_318;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten4_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten4_load = indvar_flatten4_fu_78;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten4_load_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten4_load_1 = indvar_flatten4_fu_78;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j6_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j6_load = j6_fu_82;
    end
end

always @ (*) begin
    if (((first_iter_0_reg_309 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        c_stream_blk_n = c_stream_empty_n;
    end else begin
        c_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((first_iter_0_reg_309 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        c_stream_read_local = 1'b1;
    end else begin
        c_stream_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (first_iter_08_reg_126_pp0_iter1_reg == 1'd1))) begin
        gmem_c_blk_n_AW = m_axi_gmem_c_AWREADY;
    end else begin
        gmem_c_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln68_reg_323_pp0_iter7_reg == 1'd1))) begin
        gmem_c_blk_n_B = m_axi_gmem_c_BVALID;
    end else begin
        gmem_c_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_c_blk_n_W = m_axi_gmem_c_WREADY;
    end else begin
        gmem_c_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_08_reg_126_pp0_iter1_reg == 1'd1))) begin
        m_axi_gmem_c_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_c_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln68_reg_323_pp0_iter7_reg == 1'd1))) begin
        m_axi_gmem_c_BREADY = 1'b1;
    end else begin
        m_axi_gmem_c_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_c_WVALID = 1'b1;
    end else begin
        m_axi_gmem_c_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_read = C_read_local;

assign add_ln68_fu_178_p2 = (ap_sig_allocacmp_indvar_flatten4_load + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (m_axi_gmem_c_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (m_axi_gmem_c_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((first_iter_0_reg_309 == 1'd1) & (c_stream_empty_n == 1'b0)) | ((first_iter_08_reg_126 == 1'd1) & (1'b0 == C_empty_n)));
end

always @ (*) begin
    ap_block_state3_io = ((m_axi_gmem_c_AWREADY == 1'b0) & (first_iter_08_reg_126_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = ((icmp_ln68_reg_323_pp0_iter7_reg == 1'd1) & (m_axi_gmem_c_BVALID == 1'b0));
end

always @ (*) begin
    ap_condition_217 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_395 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln68_reg_323 == 1'd0));
end

always @ (*) begin
    ap_condition_400 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln68_reg_323 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign c_stream_read = c_stream_read_local;

assign first_iter_0_fu_172_p2 = ((select_ln68_fu_164_p3 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_203_p2 = ((ap_sig_allocacmp_indvar_flatten4_load_1 == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_197_p2 = ((j_fu_191_p2 == 4'd8) ? 1'b1 : 1'b0);

assign j_fu_191_p2 = (select_ln68_fu_164_p3 + 4'd1);

assign lshr_ln71_fu_266_p2 = row_c15_fu_86 >> zext_ln71_fu_262_p1;

assign m_axi_gmem_c_ARADDR = 64'd0;

assign m_axi_gmem_c_ARBURST = 2'd0;

assign m_axi_gmem_c_ARCACHE = 4'd0;

assign m_axi_gmem_c_ARID = 1'd0;

assign m_axi_gmem_c_ARLEN = 32'd0;

assign m_axi_gmem_c_ARLOCK = 2'd0;

assign m_axi_gmem_c_ARPROT = 3'd0;

assign m_axi_gmem_c_ARQOS = 4'd0;

assign m_axi_gmem_c_ARREGION = 4'd0;

assign m_axi_gmem_c_ARSIZE = 3'd0;

assign m_axi_gmem_c_ARUSER = 1'd0;

assign m_axi_gmem_c_ARVALID = 1'b0;

assign m_axi_gmem_c_AWADDR = gmem_c_addr_reg_327;

assign m_axi_gmem_c_AWBURST = 2'd0;

assign m_axi_gmem_c_AWCACHE = 4'd0;

assign m_axi_gmem_c_AWID = 1'd0;

assign m_axi_gmem_c_AWLEN = 64'd64;

assign m_axi_gmem_c_AWLOCK = 2'd0;

assign m_axi_gmem_c_AWPROT = 3'd0;

assign m_axi_gmem_c_AWQOS = 4'd0;

assign m_axi_gmem_c_AWREGION = 4'd0;

assign m_axi_gmem_c_AWSIZE = 3'd0;

assign m_axi_gmem_c_AWUSER = 1'd0;

assign m_axi_gmem_c_RREADY = 1'b0;

assign m_axi_gmem_c_WDATA = trunc_ln71_1_reg_332;

assign m_axi_gmem_c_WID = 1'd0;

assign m_axi_gmem_c_WLAST = 1'b0;

assign m_axi_gmem_c_WSTRB = 2'd3;

assign m_axi_gmem_c_WUSER = 1'd0;

assign select_ln68_fu_164_p3 = ((ap_phi_mux_icmp_ln707_phi_fu_141_p4[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j6_load);

assign sext_ln68_fu_229_p1 = $signed(trunc_ln_fu_219_p4);

assign shl_ln_fu_255_p3 = {{trunc_ln71_reg_313_pp0_iter1_reg}, {4'd0}};

assign trunc_ln71_1_fu_272_p1 = lshr_ln71_fu_266_p2[15:0];

assign trunc_ln71_fu_187_p1 = select_ln68_fu_164_p3[2:0];

assign trunc_ln_fu_219_p4 = {{C_dout[63:1]}};

assign zext_ln71_fu_262_p1 = shl_ln_fu_255_p3;

endmodule //matrix_multiply_8x8_Loop_VITIS_LOOP_68_5_proc3
