// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="tensor_slice_test_fp16_tensor_slice_test_fp16,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=260,HLS_SYN_LUT=26,HLS_VERSION=2024_1}" *)

module tensor_slice_test_fp16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_data,
        b_data,
        ap_return
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] a_data;
input  [127:0] b_data;
output  [255:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    grp_tensor_slice_wrapper_fp16_fu_44_ap_ce;
reg    grp_tensor_slice_wrapper_fp16_fu_44_ap_start;
wire    grp_tensor_slice_wrapper_fp16_fu_44_ap_done;
wire    grp_tensor_slice_wrapper_fp16_fu_44_ap_idle;
wire    grp_tensor_slice_wrapper_fp16_fu_44_ap_ready;
wire    grp_tensor_slice_wrapper_fp16_fu_44_ap_continue;
wire   [255:0] grp_tensor_slice_wrapper_fp16_fu_44_c_data_out;
wire    grp_tensor_slice_wrapper_fp16_fu_44_c_data_out_ap_vld;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [255:0] c_data_out_fu_28;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

tensor_slice_wrapper_fp16 grp_tensor_slice_wrapper_fp16_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(grp_tensor_slice_wrapper_fp16_fu_44_ap_ce),
    .ap_start(grp_tensor_slice_wrapper_fp16_fu_44_ap_start),
    .ap_done(grp_tensor_slice_wrapper_fp16_fu_44_ap_done),
    .ap_idle(grp_tensor_slice_wrapper_fp16_fu_44_ap_idle),
    .ap_ready(grp_tensor_slice_wrapper_fp16_fu_44_ap_ready),
    .ap_continue(grp_tensor_slice_wrapper_fp16_fu_44_ap_continue),
    .a_data(a_data),
    .b_data(b_data),
    .c_data_out(grp_tensor_slice_wrapper_fp16_fu_44_c_data_out),
    .c_data_available_port(grp_tensor_slice_wrapper_fp16_fu_44_c_data_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_tensor_slice_wrapper_fp16_fu_44_c_data_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((grp_tensor_slice_wrapper_fp16_fu_44_c_data_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2)) | ((grp_tensor_slice_wrapper_fp16_fu_44_c_data_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        c_data_out_fu_28 <= grp_tensor_slice_wrapper_fp16_fu_44_c_data_out;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_tensor_slice_wrapper_fp16_fu_44_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_tensor_slice_wrapper_fp16_fu_44_ap_ce = 1'b1;
    end else begin
        grp_tensor_slice_wrapper_fp16_fu_44_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_tensor_slice_wrapper_fp16_fu_44_ap_start = 1'b1;
    end else begin
        grp_tensor_slice_wrapper_fp16_fu_44_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_tensor_slice_wrapper_fp16_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_return = c_data_out_fu_28;

assign grp_tensor_slice_wrapper_fp16_fu_44_ap_continue = 1'b1;

endmodule //tensor_slice_test_fp16
