// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matrix_multiply_8x8_Loop_VITIS_LOOP_55_3_proc2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem_b_AWVALID,
        m_axi_gmem_b_AWREADY,
        m_axi_gmem_b_AWADDR,
        m_axi_gmem_b_AWID,
        m_axi_gmem_b_AWLEN,
        m_axi_gmem_b_AWSIZE,
        m_axi_gmem_b_AWBURST,
        m_axi_gmem_b_AWLOCK,
        m_axi_gmem_b_AWCACHE,
        m_axi_gmem_b_AWPROT,
        m_axi_gmem_b_AWQOS,
        m_axi_gmem_b_AWREGION,
        m_axi_gmem_b_AWUSER,
        m_axi_gmem_b_WVALID,
        m_axi_gmem_b_WREADY,
        m_axi_gmem_b_WDATA,
        m_axi_gmem_b_WSTRB,
        m_axi_gmem_b_WLAST,
        m_axi_gmem_b_WID,
        m_axi_gmem_b_WUSER,
        m_axi_gmem_b_ARVALID,
        m_axi_gmem_b_ARREADY,
        m_axi_gmem_b_ARADDR,
        m_axi_gmem_b_ARID,
        m_axi_gmem_b_ARLEN,
        m_axi_gmem_b_ARSIZE,
        m_axi_gmem_b_ARBURST,
        m_axi_gmem_b_ARLOCK,
        m_axi_gmem_b_ARCACHE,
        m_axi_gmem_b_ARPROT,
        m_axi_gmem_b_ARQOS,
        m_axi_gmem_b_ARREGION,
        m_axi_gmem_b_ARUSER,
        m_axi_gmem_b_RVALID,
        m_axi_gmem_b_RREADY,
        m_axi_gmem_b_RDATA,
        m_axi_gmem_b_RLAST,
        m_axi_gmem_b_RID,
        m_axi_gmem_b_RFIFONUM,
        m_axi_gmem_b_RUSER,
        m_axi_gmem_b_RRESP,
        m_axi_gmem_b_BVALID,
        m_axi_gmem_b_BREADY,
        m_axi_gmem_b_BRESP,
        m_axi_gmem_b_BID,
        m_axi_gmem_b_BUSER,
        B,
        b_stream_din,
        b_stream_num_data_valid,
        b_stream_fifo_cap,
        b_stream_full_n,
        b_stream_write
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_b_AWVALID;
input   m_axi_gmem_b_AWREADY;
output  [63:0] m_axi_gmem_b_AWADDR;
output  [0:0] m_axi_gmem_b_AWID;
output  [31:0] m_axi_gmem_b_AWLEN;
output  [2:0] m_axi_gmem_b_AWSIZE;
output  [1:0] m_axi_gmem_b_AWBURST;
output  [1:0] m_axi_gmem_b_AWLOCK;
output  [3:0] m_axi_gmem_b_AWCACHE;
output  [2:0] m_axi_gmem_b_AWPROT;
output  [3:0] m_axi_gmem_b_AWQOS;
output  [3:0] m_axi_gmem_b_AWREGION;
output  [0:0] m_axi_gmem_b_AWUSER;
output   m_axi_gmem_b_WVALID;
input   m_axi_gmem_b_WREADY;
output  [7:0] m_axi_gmem_b_WDATA;
output  [0:0] m_axi_gmem_b_WSTRB;
output   m_axi_gmem_b_WLAST;
output  [0:0] m_axi_gmem_b_WID;
output  [0:0] m_axi_gmem_b_WUSER;
output   m_axi_gmem_b_ARVALID;
input   m_axi_gmem_b_ARREADY;
output  [63:0] m_axi_gmem_b_ARADDR;
output  [0:0] m_axi_gmem_b_ARID;
output  [31:0] m_axi_gmem_b_ARLEN;
output  [2:0] m_axi_gmem_b_ARSIZE;
output  [1:0] m_axi_gmem_b_ARBURST;
output  [1:0] m_axi_gmem_b_ARLOCK;
output  [3:0] m_axi_gmem_b_ARCACHE;
output  [2:0] m_axi_gmem_b_ARPROT;
output  [3:0] m_axi_gmem_b_ARQOS;
output  [3:0] m_axi_gmem_b_ARREGION;
output  [0:0] m_axi_gmem_b_ARUSER;
input   m_axi_gmem_b_RVALID;
output   m_axi_gmem_b_RREADY;
input  [7:0] m_axi_gmem_b_RDATA;
input   m_axi_gmem_b_RLAST;
input  [0:0] m_axi_gmem_b_RID;
input  [10:0] m_axi_gmem_b_RFIFONUM;
input  [0:0] m_axi_gmem_b_RUSER;
input  [1:0] m_axi_gmem_b_RRESP;
input   m_axi_gmem_b_BVALID;
output   m_axi_gmem_b_BREADY;
input  [1:0] m_axi_gmem_b_BRESP;
input  [0:0] m_axi_gmem_b_BID;
input  [0:0] m_axi_gmem_b_BUSER;
input  [63:0] B;
output  [63:0] b_stream_din;
input  [2:0] b_stream_num_data_valid;
input  [2:0] b_stream_fifo_cap;
input   b_stream_full_n;
output   b_stream_write;

reg ap_idle;
reg m_axi_gmem_b_ARVALID;
reg[63:0] m_axi_gmem_b_ARADDR;
reg m_axi_gmem_b_RREADY;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
reg    ap_block_state16_pp0_stage7_iter1;
reg    ap_block_pp0_stage7_subdone;
reg   [0:0] icmp_ln55_reg_415;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_b_blk_n_AR;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg    gmem_b_blk_n_R;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage7;
wire    ap_block_pp0_stage0;
reg    b_stream_blk_n;
reg   [63:0] B_read_reg_390;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state17_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] j22_load_reg_401;
reg   [63:0] gmem_b_addr_reg_409;
wire   [0:0] icmp_ln55_fu_209_p2;
reg   [0:0] icmp_ln55_reg_415_pp0_iter1_reg;
reg   [0:0] icmp_ln55_reg_415_pp0_iter2_reg;
wire  signed [3:0] zext_ln58_cast_fu_220_p3;
reg  signed [3:0] zext_ln58_cast_reg_419;
reg    ap_block_state10_pp0_stage1_iter1;
reg    ap_block_state18_pp0_stage1_iter2;
reg    ap_block_pp0_stage1_11001;
reg   [63:0] gmem_b_addr_1_reg_425;
wire  signed [4:0] zext_ln58_1_cast_fu_245_p3;
reg  signed [4:0] zext_ln58_1_cast_reg_431;
reg    ap_block_state11_pp0_stage2_iter1;
reg    ap_block_pp0_stage2_11001;
reg   [63:0] gmem_b_addr_2_reg_436;
reg   [63:0] gmem_b_addr_3_reg_442;
reg    ap_block_state12_pp0_stage3_iter1;
reg    ap_block_pp0_stage3_11001;
reg   [63:0] gmem_b_addr_4_reg_448;
reg   [63:0] gmem_b_addr_5_reg_454;
reg   [63:0] gmem_b_addr_6_reg_460;
reg   [63:0] gmem_b_addr_7_reg_466;
reg   [7:0] gmem_b_addr_read_reg_472;
reg   [7:0] gmem_b_addr_1_read_reg_477;
reg   [7:0] gmem_b_addr_2_read_reg_482;
reg   [7:0] gmem_b_addr_3_read_reg_487;
reg    ap_block_state13_pp0_stage4_iter1;
reg    ap_block_pp0_stage4_11001;
reg   [7:0] gmem_b_addr_4_read_reg_492;
reg    ap_block_state14_pp0_stage5_iter1;
reg    ap_block_pp0_stage5_11001;
reg   [7:0] gmem_b_addr_5_read_reg_497;
reg    ap_block_state15_pp0_stage6_iter1;
reg    ap_block_pp0_stage6_11001;
reg   [7:0] gmem_b_addr_6_read_reg_502;
reg    ap_block_pp0_stage7_11001;
reg   [7:0] gmem_b_addr_7_read_reg_507;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
wire   [63:0] add_ln58_fu_191_p2;
wire   [63:0] add_ln58_1_fu_231_p2;
wire   [63:0] add_ln58_2_fu_257_p2;
wire   [63:0] add_ln58_3_fu_275_p2;
wire   [63:0] add_ln58_4_fu_301_p2;
wire   [63:0] add_ln58_5_fu_323_p2;
wire   [63:0] add_ln58_6_fu_341_p2;
wire   [63:0] add_ln58_7_fu_359_p2;
reg   [2:0] j22_fu_66;
wire   [2:0] j_fu_203_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j22_load;
wire   [63:0] col_b_fu_370_p9;
reg    ap_block_pp0_stage1_01001;
reg    b_stream_write_local;
wire   [63:0] zext_ln55_fu_187_p1;
wire   [63:0] zext_ln58_fu_227_p1;
wire   [3:0] j22_cast_fu_242_p1;
wire   [63:0] zext_ln58_1_fu_253_p1;
wire  signed [4:0] sext_ln58_fu_268_p1;
wire   [63:0] zext_ln58_2_fu_271_p1;
wire   [4:0] zext_ln58_3_fu_286_p1;
wire   [5:0] zext_ln58_3_cast_fu_289_p3;
wire   [63:0] zext_ln58_5_fu_297_p1;
wire   [5:0] add_ln58_s_fu_312_p3;
wire   [63:0] zext_ln58_4_fu_319_p1;
wire  signed [5:0] sext_ln58_1_fu_334_p1;
wire   [63:0] zext_ln58_6_fu_337_p1;
wire  signed [5:0] sext_ln58_2_fu_352_p1;
wire   [63:0] zext_ln58_7_fu_355_p1;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter2_stage1;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [7:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_424;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 j22_fu_66 = 3'd0;
end

matrix_multiply_8x8_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone)) | ((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage1)))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_424)) begin
        j22_fu_66 <= j_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        B_read_reg_390 <= B;
        gmem_b_addr_7_read_reg_507 <= m_axi_gmem_b_RDATA;
        gmem_b_addr_reg_409 <= add_ln58_fu_191_p2;
        icmp_ln55_reg_415 <= icmp_ln55_fu_209_p2;
        icmp_ln55_reg_415_pp0_iter1_reg <= icmp_ln55_reg_415;
        icmp_ln55_reg_415_pp0_iter2_reg <= icmp_ln55_reg_415_pp0_iter1_reg;
        j22_load_reg_401 <= ap_sig_allocacmp_j22_load;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        gmem_b_addr_1_read_reg_477 <= m_axi_gmem_b_RDATA;
        gmem_b_addr_2_reg_436 <= add_ln58_2_fu_257_p2;
        zext_ln58_1_cast_reg_431[2 : 0] <= zext_ln58_1_cast_fu_245_p3[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        gmem_b_addr_1_reg_425 <= add_ln58_1_fu_231_p2;
        gmem_b_addr_read_reg_472 <= m_axi_gmem_b_RDATA;
        zext_ln58_cast_reg_419[2 : 0] <= zext_ln58_cast_fu_220_p3[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        gmem_b_addr_2_read_reg_482 <= m_axi_gmem_b_RDATA;
        gmem_b_addr_3_reg_442 <= add_ln58_3_fu_275_p2;
        gmem_b_addr_4_reg_448 <= add_ln58_4_fu_301_p2;
        gmem_b_addr_5_reg_454 <= add_ln58_5_fu_323_p2;
        gmem_b_addr_6_reg_460 <= add_ln58_6_fu_341_p2;
        gmem_b_addr_7_reg_466 <= add_ln58_7_fu_359_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        gmem_b_addr_3_read_reg_487 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        gmem_b_addr_4_read_reg_492 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        gmem_b_addr_5_read_reg_497 <= m_axi_gmem_b_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        gmem_b_addr_6_read_reg_502 <= m_axi_gmem_b_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (icmp_ln55_reg_415 == 1'd1) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln55_reg_415_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter2_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j22_load = 3'd0;
    end else begin
        ap_sig_allocacmp_j22_load = j22_fu_66;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        b_stream_blk_n = b_stream_full_n;
    end else begin
        b_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        b_stream_write_local = 1'b1;
    end else begin
        b_stream_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        gmem_b_blk_n_AR = m_axi_gmem_b_ARREADY;
    end else begin
        gmem_b_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)))) begin
        gmem_b_blk_n_R = m_axi_gmem_b_RVALID;
    end else begin
        gmem_b_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_7_reg_466;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_6_reg_460;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_5_reg_454;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_4_reg_448;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_3_reg_442;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_2_reg_436;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_1_reg_425;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        m_axi_gmem_b_ARADDR = gmem_b_addr_reg_409;
    end else begin
        m_axi_gmem_b_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        m_axi_gmem_b_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_b_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        m_axi_gmem_b_RREADY = 1'b1;
    end else begin
        m_axi_gmem_b_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_1_fu_231_p2 = (zext_ln58_fu_227_p1 + B_read_reg_390);

assign add_ln58_2_fu_257_p2 = (zext_ln58_1_fu_253_p1 + B_read_reg_390);

assign add_ln58_3_fu_275_p2 = (zext_ln58_2_fu_271_p1 + B_read_reg_390);

assign add_ln58_4_fu_301_p2 = (zext_ln58_5_fu_297_p1 + B_read_reg_390);

assign add_ln58_5_fu_323_p2 = (zext_ln58_4_fu_319_p1 + B_read_reg_390);

assign add_ln58_6_fu_341_p2 = (zext_ln58_6_fu_337_p1 + B_read_reg_390);

assign add_ln58_7_fu_359_p2 = (zext_ln58_7_fu_355_p1 + B_read_reg_390);

assign add_ln58_fu_191_p2 = (zext_ln55_fu_187_p1 + B);

assign add_ln58_s_fu_312_p3 = {{3'd5}, {j22_load_reg_401}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter2)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage1_iter1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_done_reg == 1'b1) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage2_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_done_reg == 1'b1) | ((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage2_iter1)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage3_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage3_iter1)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage4_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage4_iter1)));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001 = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage5_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage5_iter1)));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage6_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state15_pp0_stage6_iter1)));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001 = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage7_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = (((m_axi_gmem_b_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state16_pp0_stage7_iter1)));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state11_pp0_stage2_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state12_pp0_stage3_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state13_pp0_stage4_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state14_pp0_stage5_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state15_pp0_stage6_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state16_pp0_stage7_iter1 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state17_pp0_stage0_iter2 = (m_axi_gmem_b_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state18_pp0_stage1_iter2 = (b_stream_full_n == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_condition_424 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign ap_ready = ap_ready_sig;

assign b_stream_din = col_b_fu_370_p9;

assign b_stream_write = b_stream_write_local;

assign col_b_fu_370_p9 = {{{{{{{{gmem_b_addr_7_read_reg_507}, {gmem_b_addr_6_read_reg_502}}, {gmem_b_addr_5_read_reg_497}}, {gmem_b_addr_4_read_reg_492}}, {gmem_b_addr_3_read_reg_487}}, {gmem_b_addr_2_read_reg_482}}, {gmem_b_addr_1_read_reg_477}}, {gmem_b_addr_read_reg_472}};

assign icmp_ln55_fu_209_p2 = ((ap_sig_allocacmp_j22_load == 3'd7) ? 1'b1 : 1'b0);

assign j22_cast_fu_242_p1 = j22_load_reg_401;

assign j_fu_203_p2 = (ap_sig_allocacmp_j22_load + 3'd1);

assign m_axi_gmem_b_ARBURST = 2'd0;

assign m_axi_gmem_b_ARCACHE = 4'd0;

assign m_axi_gmem_b_ARID = 1'd0;

assign m_axi_gmem_b_ARLEN = 64'd1;

assign m_axi_gmem_b_ARLOCK = 2'd0;

assign m_axi_gmem_b_ARPROT = 3'd0;

assign m_axi_gmem_b_ARQOS = 4'd0;

assign m_axi_gmem_b_ARREGION = 4'd0;

assign m_axi_gmem_b_ARSIZE = 3'd0;

assign m_axi_gmem_b_ARUSER = 1'd0;

assign m_axi_gmem_b_AWADDR = 64'd0;

assign m_axi_gmem_b_AWBURST = 2'd0;

assign m_axi_gmem_b_AWCACHE = 4'd0;

assign m_axi_gmem_b_AWID = 1'd0;

assign m_axi_gmem_b_AWLEN = 32'd0;

assign m_axi_gmem_b_AWLOCK = 2'd0;

assign m_axi_gmem_b_AWPROT = 3'd0;

assign m_axi_gmem_b_AWQOS = 4'd0;

assign m_axi_gmem_b_AWREGION = 4'd0;

assign m_axi_gmem_b_AWSIZE = 3'd0;

assign m_axi_gmem_b_AWUSER = 1'd0;

assign m_axi_gmem_b_AWVALID = 1'b0;

assign m_axi_gmem_b_BREADY = 1'b0;

assign m_axi_gmem_b_WDATA = 8'd0;

assign m_axi_gmem_b_WID = 1'd0;

assign m_axi_gmem_b_WLAST = 1'b0;

assign m_axi_gmem_b_WSTRB = 1'd0;

assign m_axi_gmem_b_WUSER = 1'd0;

assign m_axi_gmem_b_WVALID = 1'b0;

assign sext_ln58_1_fu_334_p1 = zext_ln58_1_cast_reg_431;

assign sext_ln58_2_fu_352_p1 = zext_ln58_cast_reg_419;

assign sext_ln58_fu_268_p1 = zext_ln58_cast_reg_419;

assign zext_ln55_fu_187_p1 = ap_sig_allocacmp_j22_load;

assign zext_ln58_1_cast_fu_245_p3 = {{1'd1}, {j22_cast_fu_242_p1}};

assign zext_ln58_1_fu_253_p1 = $unsigned(zext_ln58_1_cast_fu_245_p3);

assign zext_ln58_2_fu_271_p1 = $unsigned(sext_ln58_fu_268_p1);

assign zext_ln58_3_cast_fu_289_p3 = {{1'd1}, {zext_ln58_3_fu_286_p1}};

assign zext_ln58_3_fu_286_p1 = j22_load_reg_401;

assign zext_ln58_4_fu_319_p1 = add_ln58_s_fu_312_p3;

assign zext_ln58_5_fu_297_p1 = zext_ln58_3_cast_fu_289_p3;

assign zext_ln58_6_fu_337_p1 = $unsigned(sext_ln58_1_fu_334_p1);

assign zext_ln58_7_fu_355_p1 = $unsigned(sext_ln58_2_fu_352_p1);

assign zext_ln58_cast_fu_220_p3 = {{1'd1}, {j22_load_reg_401}};

assign zext_ln58_fu_227_p1 = $unsigned(zext_ln58_cast_fu_220_p3);

always @ (posedge ap_clk) begin
    zext_ln58_cast_reg_419[3] <= 1'b1;
    zext_ln58_1_cast_reg_431[4:3] <= 2'b10;
end

endmodule //matrix_multiply_8x8_Loop_VITIS_LOOP_55_3_proc2
